# -*- coding: utf-8 -*-
"""Single source of truth: business data, fleet, tours, routes, FAQ."""

SITE = "https://www.miamibeachbikesandtours.com"

BIZ = {
    "name": "Miami Beach Bikes & Tours",
    "legal": "Miami Beach Bikes & Tours",
    "tagline": "Ride more. Worry less.",
    "phone": "+1-305-830-9440",
    "phone_pretty": "(305) 830-9440",
    "email": "hello@miamibeachbikesandtours.com",
    "street": "233 14th Street",
    "city": "Miami Beach",
    "region": "FL",
    "zip": "33139",
    "country": "US",
    "lat": "25.78730",
    "lng": "-80.13180",
    "hours": "Mo-Su 09:00-20:00",
    "hours_pretty": "Every day · 9:00 AM – 8:00 PM",
    "price_range": "$$",
    "areas": ["South Beach", "Mid-Beach", "North Beach", "Downtown Miami",
              "Brickell", "Wynwood", "Star Island", "Venetian Islands", "Key Biscayne"],
}

# --- Fleet ------------------------------------------------------------------
# cat drives the on-page chip filter. price = headline hourly rate (USD).
FLEET = [
    {
        "slug": "beach-cruiser", "cat": "bikes family", "img": "fleet-cruiser",
        "name": "Beach Cruiser", "tag": "Most booked",
        "hook": "The classic South Beach ride. Fat tires, wide saddle, one gear and zero stress along the Ocean Drive promenade.",
        "meta": ["Ages 13+", "Helmet + lock", "Basket"],
        "price": 12, "unit": "hour",
        "rates": [("1 hour", 12), ("2 hours", 18), ("4 hours", 22), ("24 hours", 28), ("1 week", 75)],
    },
    {
        "slug": "electric-bike", "cat": "bikes electric", "img": "fleet-ebike",
        "name": "Electric Bike", "tag": "Go further",
        "hook": "Pedal-assist up to 20 mph. Wynwood, Bayside, Downtown and back without breaking a sweat in the Miami sun.",
        "meta": ["Ages 16+", "40+ mi range", "Route map"],
        "price": 25, "unit": "hour",
        "rates": [("1 hour", 25), ("2 hours", 40), ("4 hours", 55), ("24 hours", 89), ("1 week", 320)],
    },
    {
        "slug": "segway", "cat": "segways electric", "img": "fleet-segway",
        "name": "Segway", "tag": "Authorized dealer",
        "hook": "Self-balancing, ridiculously fun and easier than it looks. Free training session before every ride.",
        "meta": ["Ages 14+", "Training included", "Guided only"],
        "price": 45, "unit": "30 min",
        "rates": [("30 minutes", 45), ("1 hour", 65), ("1.5 hours", 85)],
    },
    {
        "slug": "rollerblades", "cat": "skates family", "img": "fleet-skate",
        "name": "Rollerblades", "tag": "Lincoln Rd favorite",
        "hook": "Skate the Beachwalk like a local. Sizes for the whole family, pads and helmet included with every pair.",
        "meta": ["Kids + adults", "Pads included", "All sizes"],
        "price": 12, "unit": "hour",
        "rates": [("1 hour", 12), ("2 hours", 18), ("4 hours", 20), ("24 hours", 25), ("1 week", 65)],
    },
    {
        "slug": "adult-tricycle", "cat": "bikes family", "img": "fleet-trike",
        "name": "Adult Tricycle", "tag": "Extra stable",
        "hook": "Three wheels, big rear basket, zero balance required. The pick for beach picnics and easy cruising.",
        "meta": ["Ages 16+", "Cargo basket", "No balance needed"],
        "price": 18, "unit": "hour",
        "rates": [("1 hour", 18), ("2 hours", 28), ("4 hours", 35), ("24 hours", 45), ("1 week", 120)],
    },
    {
        "slug": "kids-bikes", "cat": "family bikes", "img": "fleet-kids",
        "name": "Kids Bikes & Tandems", "tag": "Family ready",
        "hook": "Kids bikes from 12\" to 24\", tandems, baby seats and trailers. Everybody rolls, nobody gets left behind.",
        "meta": ["Baby seats", "Trailers", "Tandems"],
        "price": 10, "unit": "hour",
        "rates": [("Kids bike · 1 hour", 10), ("Kids bike · 24 hours", 22),
                  ("Tandem · 1 hour", 22), ("Tandem · 24 hours", 55), ("Baby seat", 5)],
    },
]

# --- Tours ------------------------------------------------------------------
TOURS = [
    {
        "slug": "art-deco-segway-tour", "cat": "segway short", "img": "tour-artdeco",
        "name": "Art Deco Segway Tour", "tag": "Signature",
        "hook": "Glide past the pastel facades of Ocean Drive while your guide unpacks 1930s Miami Beach — neon, curves and porthole windows.",
        "meta": ["30 · 60 · 90 min", "Ages 14+", "Training included"],
        "price": 45, "dur": "PT30M", "dur_pretty": "30 min",
        "stops": ["Art Deco Historic District", "Ocean Drive", "Lummus Park", "Española Way"],
        "options": [("30 minutes", 45), ("1 hour", 65), ("1.5 hours", 85)],
    },
    {
        "slug": "ocean-drive-bike-tour", "cat": "bike short", "img": "tour-oceandrive",
        "name": "Ocean Drive Bike Tour", "tag": "Best for families",
        "hook": "An easy, flat, fully guided loop of the beachfront: lifeguard towers, Lummus Park, Ocean Drive and the Beachwalk.",
        "meta": ["90 min", "All ages", "Water + helmet"],
        "price": 39, "dur": "PT1H30M", "dur_pretty": "90 min",
        "stops": ["Lummus Park", "Ocean Drive", "12th St lifeguard tower", "Beachwalk"],
        "options": [("90 minutes", 39), ("Private group", 149)],
    },
    {
        "slug": "star-island-south-pointe-tour", "cat": "bike half", "img": "tour-starisland",
        "name": "Star Island & South Pointe Tour", "tag": "Photo run",
        "hook": "Over the MacArthur Causeway to the celebrity mansions of Star Island, then down to South Pointe Park for the cruise-ship parade.",
        "meta": ["2.5 hours", "Ages 12+", "E-bike option"],
        "price": 59, "dur": "PT2H30M", "dur_pretty": "2.5 hours",
        "stops": ["MacArthur Causeway", "Star Island", "South Pointe Park", "Pier & jetty"],
        "options": [("Cruiser · 2.5 h", 59), ("E-bike · 2.5 h", 79)],
    },
    {
        "slug": "sunset-electric-bike-tour", "cat": "electric half", "img": "tour-sunset",
        "name": "Sunset Electric Bike Tour", "tag": "Golden hour",
        "hook": "Chase the light from South Beach to the Venetian Islands and watch the skyline switch on across Biscayne Bay.",
        "meta": ["2 hours", "Ages 16+", "E-bike included"],
        "price": 75, "dur": "PT2H", "dur_pretty": "2 hours",
        "stops": ["Venetian Causeway", "Belle Isle", "Biscayne Bay", "Lincoln Road"],
        "options": [("2 hours", 75), ("Private group", 260)],
    },
    {
        "slug": "wynwood-downtown-ebike-tour", "cat": "electric full", "img": "fleet-ebike",
        "name": "Wynwood & Downtown E-Bike Tour", "tag": "Street art",
        "hook": "Cross the bay and ride the murals of Wynwood, then Bayside, Brickell and the Miami River. Our longest, best-value ride.",
        "meta": ["4 hours", "Ages 16+", "Snack stop"],
        "price": 119, "dur": "PT4H", "dur_pretty": "4 hours",
        "stops": ["Wynwood Walls", "Design District", "Bayside Marketplace", "Brickell"],
        "options": [("4 hours", 119), ("Private group", 420)],
    },
    {
        "slug": "parasailing-south-beach", "cat": "water full", "img": "tour-parasail",
        "name": "South Beach Parasailing", "tag": "Adrenaline",
        "hook": "600 feet above the Atlantic with the whole Miami Beach coastline under your feet. Solo, tandem or triple flights.",
        "meta": ["~1 hour", "Ages 6+", "No experience"],
        "price": 95, "dur": "PT1H", "dur_pretty": "~1 hour",
        "stops": ["Marina check-in", "Boat ride", "Flight", "Splash-down (optional)"],
        "options": [("Single flight", 95), ("Tandem flight", 175), ("Triple flight", 240)],
    },
]

# --- Routes (GEO / local-intent content) -----------------------------------
ROUTES = [
    {"name": "The Beachwalk Classic", "km": "8 km · 5 mi", "time": "45 min", "level": "Easy",
     "from": "233 14th St", "to": "South Pointe Park",
     "desc": "Straight down the paved Beachwalk to South Pointe Park and back. Flat, car-free, shaded in stretches, and the single best first ride in South Beach.",
     "stops": ["Lummus Park", "Ocean Drive", "South Pointe Pier", "Joe's Stone Crab"]},
    {"name": "Art Deco Neon Loop", "km": "6 km · 3.7 mi", "time": "40 min", "level": "Easy",
     "from": "233 14th St", "to": "Española Way",
     "desc": "Ocean Drive, Collins, Washington and Española Way. Ride it after 7 PM when the neon fires up and the whole district turns pink and turquoise.",
     "stops": ["Colony Hotel", "Española Way", "Lincoln Road Mall", "Washington Ave"]},
    {"name": "Star Island & the Causeway", "km": "16 km · 10 mi", "time": "1 h 15", "level": "Moderate",
     "from": "233 14th St", "to": "Star Island",
     "desc": "Protected bike path along the MacArthur Causeway to Palm, Hibiscus and Star Island. Cruise-ship views on one side, mansions on the other.",
     "stops": ["MacArthur Causeway", "Star Island gate", "Terminal Island", "South Pointe"]},
    {"name": "Venetian Islands Sunset", "km": "14 km · 8.7 mi", "time": "1 h", "level": "Moderate",
     "from": "233 14th St", "to": "Belle Isle",
     "desc": "Low-traffic island hopping across the Venetian Causeway. The classic golden-hour route with the Downtown skyline straight ahead.",
     "stops": ["Belle Isle", "Di Lido Island", "Rivo Alto", "Sunset Harbour"]},
    {"name": "Wynwood Mural Run", "km": "26 km · 16 mi", "time": "2 h", "level": "E-bike",
     "from": "233 14th St", "to": "Wynwood Walls",
     "desc": "Our e-bike route across the bay into the street-art district, looping back through the Design District and Bayside. Take the battery.",
     "stops": ["Wynwood Walls", "NW 2nd Ave", "Design District", "Bayside Marketplace"]},
    {"name": "North Beach & Boardwalk", "km": "20 km · 12.4 mi", "time": "1 h 30", "level": "Moderate",
     "from": "233 14th St", "to": "North Beach Oceanside Park",
     "desc": "Head north along the boardwalk past Mid-Beach, the Faena District and the Fontainebleau all the way to the quiet end of the island.",
     "stops": ["Faena District", "Fontainebleau", "Indian Beach Park", "Oceanside Park"]},
]

# --- FAQ (AEO: short answer first, then detail) -----------------------------
FAQ = [
    ("Where can I rent a bike in South Beach?",
     "At our shop at 233 14th Street, Miami Beach, FL 33139 — one block from Ocean Drive and the Beachwalk, open every day from 9 AM to 8 PM. Walk-ins are welcome and we also deliver across South Beach."),
    ("How much does it cost to rent a bike in Miami Beach?",
     "Beach cruisers start at $12 for one hour and $28 for a full 24 hours. Electric bikes start at $25 per hour, rollerblades at $12 per hour and adult tricycles at $18 per hour. Helmet, lock and bottled water are included with every rental."),
    ("Do I need to book in advance?",
     "No. Walk-ins are welcome all day, every day. Booking ahead is recommended in high season (December to April) and on weekends, and it is required for Segway tours, which run on fixed departure times."),
    ("Do you deliver bikes to my hotel?",
     "Yes. We deliver and pick up at hotels, Airbnbs and condos across South Beach and Mid-Beach. Delivery is free on rentals of 24 hours or more within South Beach; shorter rentals and other areas carry a flat delivery fee."),
    ("How long can I keep the bike?",
     "From one hour up to 60 days. Daily, weekly and monthly rates drop sharply the longer you ride — a week costs about the same as three single days."),
    ("What is included with a rental?",
     "Every rental includes a helmet, a lock, a bottle of water, a Miami Beach route map and roadside support by phone while you are out riding."),
    ("How old do you have to be to ride a Segway?",
     "Riders must be at least 14 years old for Segway tours; riders under 18 must be accompanied by an adult. Every tour begins with a free training session, so no previous experience is needed."),
    ("Is Miami Beach safe for cycling?",
     "Yes. South Beach is flat, compact and covered by protected bike lanes plus the car-free Beachwalk that runs the length of the sand. Florida law requires helmets for riders under 16 and we provide one with every rental."),
    ("What is your cancellation policy?",
     "Cancellations 30 or more days before the reservation receive a full refund; 15 to 30 days receive 50%; 8 to 14 days receive 25%; and cancellations within 7 days of the reservation are non-refundable. All reservations are pre-paid in US dollars."),
    ("Do you repair bikes, e-bikes and scooters?",
     "Yes. Our shop handles flat tires, brakes, gears, batteries and full tune-ups for bikes, e-bikes and scooters, with most walk-in repairs finished the same day."),
]

REVIEWS = [
    ("The Art Deco Segway tour was the highlight of our trip. Twenty minutes of training and my mother-in-law was gliding down Ocean Drive like a pro.",
     "Danielle R. · Chicago"),
    ("Rented four bikes and a baby seat for a week. They delivered to our hotel on 16th, swapped a flat the same afternoon, no drama at all.",
     "The Okonkwo family · Atlanta"),
    ("Took the e-bikes to Wynwood and back. Best $89 we spent in Miami — we saw more of the city in one day than in the previous three.",
     "Marco V. · Milan"),
    ("Skated the Beachwalk at sunset with my kids. Pads, helmets and good advice on where to go. Super friendly crew.",
     "Yasmin K. · Toronto"),
    ("Parasailing over South Beach was unreal. Easy booking right at the shop and the boat crew made my ten-year-old feel completely safe.",
     "Greg P. · Boston"),
    ("They fixed my own bike's brakes in under an hour while I got coffee. Real mechanics, fair price, locals' spot.",
     "Andrés M. · Miami Beach"),
]
