# -*- coding: utf-8 -*-
"""Single source of truth: business data, fleet, tours, routes, FAQ."""

SITE = "https://www.miamibeachbikesandtours.com"

BIZ = {
    "name": "Miami Beach Bikes & Tours",
    "legal": "Miami Beach Bikes & Tours",
    "tagline": "Ride more. Worry less.",
    "happy_hour": "Happy hour 1–4 PM: one extra hour free on any rental",
    "phone": "+1-305-830-9440",
    "phone_pretty": "(305) 830-9440",
    "email": "hello@miamibeachbikesandtours.com",
    "street": "233 14th Street",
    "cross": "at the corner of Washington Avenue",
    "city": "Miami Beach",
    "region": "FL",
    "zip": "33139",
    "country": "US",
    "lat": "25.78730",
    "lng": "-80.13180",
    "hours": "Mo-Su 09:00-20:00",
    "hours_pretty": "Every day · 9:00 AM – 8:00 PM",
    "price_range": "$$",
    "areas": ["South Beach", "Mid-Beach", "North Beach", "Downtown Miami",
              "Brickell", "Wynwood", "Star Island", "Venetian Islands", "Key Biscayne", "Everglades", "Key West"],
}

# --- Fleet ------------------------------------------------------------------
# cat drives the on-page chip filter. price = headline hourly rate (USD).
FLEET = [
    {
        "slug": "beach-cruiser", "cat": "bikes family", "img": "fleet-cruiser",
        "name": "Beach Cruiser", "tag": "Most booked",
        "hook": "The classic South Beach ride. Fat tires, wide saddle, one gear and zero stress along the Ocean Drive promenade.",
        "meta": ["Ages 13+", "Helmet + lock", "Basket $5"],
        "price": 12, "unit": "hour",
        "rates": [("1 hour", 12), ("2 hours", 18), ("4 hours", 22), ("All day 9am–8pm", 28), ("1 week", 75)],
    },
    {
        "slug": "fat-tire-bike", "cat": "bikes", "img": "fleet-cruiser",
        "name": "Fat Tire Beach Bike", "tag": "Rides on sand",
        "hook": "Four-inch tires built for the hard-pack sand at the waterline. The only bike here you can actually ride on the beach.",
        "meta": ["Ages 16+", "Sand-capable", "Helmet + lock"],
        "price": 18, "unit": "hour",
        "rates": [("1 hour", 18), ("2 hours", 26), ("4 hours", 35), ("All day 9am–8pm", 45), ("1 week", 160)],
    },
    {
        "slug": "electric-bike", "cat": "bikes electric", "img": "fleet-ebike",
        "name": "Electric Bike", "tag": "Go further",
        "hook": "Pedal-assist up to 20 mph. Wynwood, Bayside, Downtown and back without breaking a sweat in the Miami sun.",
        "meta": ["Ages 16+", "40+ mi range", "Route map"],
        "price": 25, "unit": "hour",
        "rates": [("1 hour", 25), ("2 hours", 40), ("4 hours", 55), ("All day 9am–8pm", 89), ("1 week", 320)],
    },
    {
        "slug": "electric-tandem", "cat": "bikes electric family", "img": "fleet-ebike",
        "name": "Electric Tandem", "tag": "Two riders, one battery",
        "hook": "A pedal-assist tandem for two. The strongest rider sets the pace and nobody gets dropped halfway across the causeway.",
        "meta": ["2 riders", "Ages 16+", "Priced per group"],
        "price": 45, "unit": "hour",
        "rates": [("1 hour", 45), ("2 hours", 70), ("4 hours", 95), ("All day 9am–8pm", 130)],
    },
    {
        "slug": "trikke", "cat": "trikke electric", "img": "fleet-trike",
        "name": "Trikke", "tag": "Our namesake",
        "hook": "The three-wheeled carving vehicle this shop was built around. You steer it by leaning, it is easier than a bike, and nothing turns more heads on Ocean Drive.",
        "meta": ["Ages 14+", "Training included", "Electric option"],
        "price": 35, "unit": "hour",
        "rates": [("30 minutes", 25), ("1 hour", 35), ("2 hours", 55), ("Half day", 79)],
    },
    {
        "slug": "segway", "cat": "segways electric", "img": "fleet-segway",
        "name": "Segway", "tag": "Authorized dealer",
        "hook": "Self-balancing, ridiculously fun and easier than it looks. Free training before every ride — and we sell and service them too.",
        "meta": ["Ages 14+", "Training included", "Guided tours"],
        "price": 49, "unit": "guided tour",
        "rates": [("Guided tour · from", 49), ("Sales, parts & service", 0)],
    },
    {
        "slug": "side-by-side", "cat": "family bikes", "img": "fleet-trike",
        "name": "Side-by-Side & Tandem", "tag": "Ride together",
        "hook": "Four wheels, two seats, side by side — plus classic tandems. Talk the whole way instead of shouting over your shoulder.",
        "meta": ["2–4 riders", "Canopy", "Basket"],
        "price": 22, "unit": "hour",
        "rates": [("Tandem · 1 hour", 22), ("Tandem · all day", 55), ("Side-by-side · 1 hour", 39), ("Side-by-side · all day", 89)],
    },
    {
        "slug": "adult-tricycle", "cat": "bikes family", "img": "fleet-trike",
        "name": "Adult Tricycle", "tag": "Extra stable",
        "hook": "Three wheels, big rear basket, zero balance required. The pick for beach picnics and easy cruising.",
        "meta": ["Ages 16+", "Cargo basket", "No balance needed"],
        "price": 18, "unit": "hour",
        "rates": [("1 hour", 18), ("2 hours", 28), ("4 hours", 35), ("All day 9am–8pm", 45), ("1 week", 120)],
    },
    {
        "slug": "rollerblades", "cat": "skates family", "img": "fleet-skate",
        "name": "Rollerblades", "tag": "Lincoln Rd favorite",
        "hook": "Skate the Beachwalk like a local. Sizes for the whole family, pads and helmet included with every pair.",
        "meta": ["Kids + adults", "Pads included", "All sizes"],
        "price": 12, "unit": "hour",
        "rates": [("1 hour", 12), ("2 hours", 18), ("4 hours", 20), ("All day 9am–8pm", 25), ("1 week", 65)],
    },
    {
        "slug": "kids-bikes", "cat": "family bikes", "img": "fleet-kids",
        "name": "Kids Bikes & Baby Seats", "tag": "Family ready",
        "hook": "Kids bikes from 12 to 24 inches, baby seats, trailers and training wheels. Everybody rolls, nobody gets left behind at the hotel.",
        "meta": ["Baby seats $5", "Trailers", "Training wheels"],
        "price": 10, "unit": "hour",
        "rates": [("Kids bike · 1 hour", 10), ("Kids bike · all day", 22), ("Baby seat", 5), ("Trailer · all day", 30), ("Basket add-on", 5)],
    },
]

# --- Tours ------------------------------------------------------------------
TOURS = [
    {
        "slug": "ocean-drive-segway-tour", "cat": "segway short", "img": "tour-oceandrive",
        "name": "Ocean Drive Segway Tour", "tag": "Best first ride",
        "hook": "The short one, and the one everybody starts with. Ocean Drive, Lummus Park and the beachfront on a Segway, training included.",
        "meta": ["1 hour", "Ages 14+", "Min. 2 riders"],
        "price": 49, "dur": "PT1H", "dur_pretty": "1 hour",
        "stops": ["Ocean Drive", "Lummus Park", "10th St Auditorium", "Beachwalk"],
        "options": [("Per person", 49)],
    },
    {
        "slug": "star-island-segway-tour", "cat": "segway short", "img": "tour-starisland",
        "name": "Star Island Segway Tour", "tag": "Celebrity homes",
        "hook": "Over the MacArthur Causeway on the protected path to the gates of Star Island — cruise-ship terminal on one side, mansions on the other.",
        "meta": ["1 hour", "Ages 14+", "Min. 2 riders"],
        "price": 69, "dur": "PT1H", "dur_pretty": "1 hour",
        "stops": ["MacArthur Causeway", "Star Island", "Palm & Hibiscus Islands", "Terminal Island"],
        "options": [("Per person", 69)],
    },
    {
        "slug": "south-beach-segway-tour", "cat": "segway half", "img": "fleet-segway",
        "name": "South Beach Segway Tour", "tag": "The full island",
        "hook": "The long version: Ocean Drive, Española Way, Lincoln Road, South Pointe Park and the pier, with stops long enough to actually take pictures.",
        "meta": ["2 hours", "Ages 14+", "Min. 2 riders"],
        "price": 79, "dur": "PT2H", "dur_pretty": "2 hours",
        "stops": ["Ocean Drive", "Española Way", "Lincoln Road", "South Pointe Park"],
        "options": [("Per person", 79)],
    },
    {
        "slug": "art-deco-segway-tour", "cat": "segway half", "img": "tour-artdeco",
        "name": "Miami Beach Art Deco Segway Tour", "tag": "Signature",
        "hook": "Glide the Art Deco Historic District while your guide unpacks 1930s Miami Beach — neon, porthole windows, eyebrows and racing stripes.",
        "meta": ["2 hours", "Ages 14+", "Min. 2 riders"],
        "price": 79, "dur": "PT2H", "dur_pretty": "2 hours",
        "stops": ["Art Deco Historic District", "Colony Hotel", "Española Way", "Washington Avenue"],
        "options": [("Per person", 79)],
    },
    {
        "slug": "millionaires-row-segway-tour", "cat": "segway half", "img": "tour-sunset",
        "name": "Miami Millionaire's Row Segway Tour", "tag": "Longest ride",
        "hook": "North up Collins past the Faena District, the Fontainebleau and the oceanfront estates of Millionaire's Row. Our biggest Segway route.",
        "meta": ["2.5 hours", "Ages 14+", "Min. 2 riders"],
        "price": 89, "dur": "PT2H30M", "dur_pretty": "2.5 hours",
        "stops": ["Faena District", "Fontainebleau", "Millionaire's Row", "Indian Beach Park"],
        "options": [("Per person", 89)],
    },
    {
        "slug": "panoramic-night-chariot-tour", "cat": "night private", "img": "tour-sunset",
        "name": "Panoramic Night Private Chariot Tour", "tag": "After dark",
        "hook": "Private, after-dark and lit up: the neon of Ocean Drive, the causeway lights and the Downtown skyline reflected across Biscayne Bay.",
        "meta": ["Private group", "Evening", "All ages"],
        "price": 119, "dur": "PT2H", "dur_pretty": "~2 hours",
        "stops": ["Ocean Drive neon", "MacArthur Causeway", "Biscayne Bay", "Downtown skyline"],
        "options": [("Private group · from", 119)],
    },
]

# --- Adventures: the off-the-island half of the catalogue -------------------
ADVENTURES = [
    {
        "slug": "everglades-airboat-adventure", "cat": "nature day", "img": "routes-map",
        "name": "Everglades Airboat Adventure", "tag": "Most booked day trip",
        "hook": "Out to the River of Grass for an airboat run through the sawgrass, a wildlife show and alligators at close range. Transport from South Beach included.",
        "meta": ["4.5 hours", "All ages", "Hotel pickup"],
        "price": 69, "dur": "PT4H30M", "dur_pretty": "4.5 hours",
        "stops": ["Hotel pickup", "Airboat ride", "Wildlife show", "Alligator encounter"],
        "options": [("Per person", 69)],
    },
    {
        "slug": "key-west-day-trip", "cat": "day", "img": "tour-oceandrive",
        "name": "Key West Day Trip", "tag": "Full day",
        "hook": "The whole Overseas Highway, Seven Mile Bridge included, with around six free hours on the island for Duval Street, Mallory Square and the Southernmost Point.",
        "meta": ["Full day", "All ages", "Hotel pickup"],
        "price": 99, "dur": "P1D", "dur_pretty": "Full day",
        "stops": ["Seven Mile Bridge", "Duval Street", "Mallory Square", "Southernmost Point"],
        "options": [("Per person · from", 99)],
    },
    {
        "slug": "miami-city-tour", "cat": "city day", "img": "tour-artdeco",
        "name": "Miami City Tour", "tag": "Orientation",
        "hook": "Half a day across the whole city: Little Havana, Wynwood, the Design District, Brickell, Coconut Grove and back over the bay.",
        "meta": ["~4 hours", "All ages", "Hotel pickup"],
        "price": 49, "dur": "PT4H", "dur_pretty": "~4 hours",
        "stops": ["Little Havana", "Wynwood Walls", "Design District", "Coconut Grove"],
        "options": [("Per person · from", 49)],
    },
    {
        "slug": "jet-ski-rental", "cat": "water", "img": "tour-parasail",
        "name": "Jet Ski Rental", "tag": "Adrenaline",
        "hook": "Open throttle on Biscayne Bay with the Downtown skyline as the backdrop. No licence needed, full safety brief before you launch.",
        "meta": ["30 or 60 min", "Ages 16+ to drive", "2 riders"],
        "price": 99, "dur": "PT1H", "dur_pretty": "30–60 min",
        "stops": ["Marina check-in", "Safety brief", "Biscayne Bay run", "Skyline views"],
        "options": [("30 minutes", 99), ("1 hour", 159)],
    },
    {
        "slug": "parasailing-south-beach", "cat": "water", "img": "tour-parasail",
        "name": "South Beach Parasailing", "tag": "600 feet up",
        "hook": "Six hundred feet above the Atlantic with the whole Miami Beach coastline under your feet. Solo, tandem or triple flights, optional splash-down.",
        "meta": ["~1 hour", "Ages 6+", "No experience"],
        "price": 95, "dur": "PT1H", "dur_pretty": "~1 hour",
        "stops": ["Marina check-in", "Boat ride", "Flight", "Optional splash-down"],
        "options": [("Single flight", 95), ("Tandem flight", 175), ("Triple flight", 240)],
    },
    {
        "slug": "helicopter-ride-miami", "cat": "air", "img": "tour-sunset",
        "name": "Miami Helicopter Ride", "tag": "Bucket list",
        "hook": "Flight over South Beach, Star Island, the Port of Miami and the Downtown skyline. The fastest way to understand how this city is laid out.",
        "meta": ["15–30 min", "All ages", "2–3 passengers"],
        "price": 149, "dur": "PT30M", "dur_pretty": "15–30 min",
        "stops": ["South Beach", "Star Island", "Port of Miami", "Downtown skyline"],
        "options": [("Per person · from", 149)],
    },
]

# --- Routes (GEO / local-intent content) -----------------------------------
ROUTES = [
    {"name": "The Beachwalk Classic", "km": "8 km · 5 mi", "time": "45 min", "level": "Easy",
     "from": "233 14th St", "to": "South Pointe Park",
     "desc": "Straight down the paved Beachwalk to South Pointe Park and back. Flat, car-free, shaded in stretches, and the single best first ride in South Beach.",
     "stops": ["Lummus Park", "Ocean Drive", "South Pointe Pier", "Joe's Stone Crab"]},
    {"name": "Art Deco Neon Loop", "km": "6 km · 3.7 mi", "time": "40 min", "level": "Easy",
     "from": "233 14th St", "to": "Española Way",
     "desc": "Ocean Drive, Collins, Washington and Española Way. Ride it after 7 PM when the neon fires up and the whole district turns pink and turquoise.",
     "stops": ["Colony Hotel", "Española Way", "Lincoln Road Mall", "Washington Ave"]},
    {"name": "Star Island & the Causeway", "km": "16 km · 10 mi", "time": "1 h 15", "level": "Moderate",
     "from": "233 14th St", "to": "Star Island",
     "desc": "Protected bike path along the MacArthur Causeway to Palm, Hibiscus and Star Island. Cruise-ship views on one side, mansions on the other.",
     "stops": ["MacArthur Causeway", "Star Island gate", "Terminal Island", "South Pointe"]},
    {"name": "Venetian Islands Sunset", "km": "14 km · 8.7 mi", "time": "1 h", "level": "Moderate",
     "from": "233 14th St", "to": "Belle Isle",
     "desc": "Low-traffic island hopping across the Venetian Causeway. The classic golden-hour route with the Downtown skyline straight ahead.",
     "stops": ["Belle Isle", "Di Lido Island", "Rivo Alto", "Sunset Harbour"]},
    {"name": "Wynwood Mural Run", "km": "26 km · 16 mi", "time": "2 h", "level": "E-bike",
     "from": "233 14th St", "to": "Wynwood Walls",
     "desc": "Our e-bike route across the bay into the street-art district, looping back through the Design District and Bayside. Take the battery.",
     "stops": ["Wynwood Walls", "NW 2nd Ave", "Design District", "Bayside Marketplace"]},
    {"name": "North Beach & Boardwalk", "km": "20 km · 12.4 mi", "time": "1 h 30", "level": "Moderate",
     "from": "233 14th St", "to": "North Beach Oceanside Park",
     "desc": "Head north along the boardwalk past Mid-Beach, the Faena District and the Fontainebleau all the way to the quiet end of the island.",
     "stops": ["Faena District", "Fontainebleau", "Indian Beach Park", "Oceanside Park"]},
]

# --- FAQ (AEO: short answer first, then detail) -----------------------------
FAQ = [
    ("Where can I rent a bike in South Beach?",
     "At our shop at 233 14th Street, Miami Beach, FL 33139 — at the corner of Washington Avenue, one block from Ocean Drive and the Beachwalk. We are open every day from 9 AM to 8 PM. Walk-ins are welcome and we also deliver across South Beach."),
    ("How much does it cost to rent a bike in Miami Beach?",
     "Beach cruisers start at $12 for one hour and $28 for all day (9 AM to 8 PM). Fat tire beach bikes start at $18/hour, electric bikes at $25/hour, adult tricycles at $18/hour, tandems at $22/hour and rollerblades at $12/hour. Helmet, lock and bottled water are included with every rental."),
    ("What is the happy hour special?",
     "Rent between 1 PM and 4 PM and you get one extra hour free on any bike, trike or skate rental. It applies to walk-ins and reservations alike, every day of the week."),
    ("How much are the Segway tours?",
     "The Ocean Drive Segway Tour is $49 per person for one hour. The Star Island Segway Tour is $69, the South Beach and Art Deco Segway Tours are $79 each for two hours, and the Miami Millionaire's Row Segway Tour is $89 for 2.5 hours. All Segway tours include training and require a minimum of two riders."),
    ("What is a Trikke?",
     "A Trikke is a three-wheeled carving vehicle you steer by leaning your body from side to side — no pedals, no balancing act. It is the machine this shop is named after, it takes about five minutes to learn, and we rent it from $25 for 30 minutes."),
    ("Do I need to book in advance?",
     "For rentals, no — walk-ins are welcome all day, every day. Booking ahead is recommended in high season (December to April) and on weekends, and it is required for Segway tours, day trips, jet skis, parasailing and helicopter rides, which all run on fixed departure times."),
    ("Do you deliver bikes to my hotel?",
     "Yes. We deliver and pick up at hotels, Airbnbs and condos across South Beach and Mid-Beach. Delivery is free on rentals of 24 hours or more within South Beach; shorter rentals and other areas carry a flat delivery fee. Day trips and adventures include hotel pickup."),
    ("How long can I keep the bike?",
     "From one hour up to 60 days. Daily, weekly and monthly rates drop sharply the longer you ride — a week costs about the same as three single days."),
    ("What is included with a rental?",
     "Every rental includes a helmet, a lock, a bottle of water, a Miami Beach route map and roadside support by phone while you are out riding. Baskets and baby seats are $5 each."),
    ("How old do you have to be to ride a Segway or a Trikke?",
     "Riders must be at least 14 years old; riders under 18 must be accompanied by an adult. Every tour begins with a free training session, so no previous experience is needed, and Segway PT tours require no deposit at booking or in store."),
    ("What else do you book besides bikes and Segways?",
     "Everglades airboat adventures (4.5 hours, $69), Key West day trips, Miami city tours, jet ski rentals, South Beach parasailing and helicopter rides over the city. All of them can be booked at the shop or by phone, and most include hotel pickup."),
    ("Is Miami Beach safe for cycling?",
     "Yes. South Beach is flat, compact and covered by protected bike lanes plus the car-free Beachwalk that runs the length of the sand. Florida law requires helmets for riders under 16 and we provide one with every rental."),
    ("Do you repair bikes, e-bikes and scooters?",
     "Yes. Our shop handles flat tires, brakes, gears, batteries and full tune-ups for bikes, e-bikes and scooters, with most walk-in repairs finished the same day. We are also an authorized Segway dealer for sales, parts and service."),
    ("What is your cancellation policy?",
     "Cancellations 30 or more days before the reservation receive a full refund; 15 to 30 days receive 50%; 8 to 14 days receive 25%; and cancellations within 7 days of the reservation are non-refundable. All reservations are pre-paid in US dollars."),
]

REVIEWS = [
    ("The Art Deco Segway tour was the highlight of our trip. Twenty minutes of training and my mother-in-law was gliding down Ocean Drive like a pro.",
     "Danielle R. · Chicago"),
    ("Rented four bikes and a baby seat for a week. They delivered to our hotel on 16th, swapped a flat the same afternoon, no drama at all.",
     "The Okonkwo family · Atlanta"),
    ("Took the e-bikes to Wynwood and back. Best $89 we spent in Miami — we saw more of the city in one day than in the previous three.",
     "Marco V. · Milan"),
    ("Skated the Beachwalk at sunset with my kids. Pads, helmets and good advice on where to go. Super friendly crew.",
     "Yasmin K. · Toronto"),
    ("Parasailing over South Beach was unreal. Easy booking right at the shop and the boat crew made my ten-year-old feel completely safe.",
     "Greg P. · Boston"),
    ("They fixed my own bike's brakes in under an hour while I got coffee. Real mechanics, fair price, locals' spot.",
     "Andrés M. · Miami Beach"),
]
