# -*- coding: utf-8 -*-
"""Spanish content. Proper nouns stay in English on purpose."""

PHRASES = {
    # durations and rates
    "1 hour": "1 hora", "2 hours": "2 horas", "4 hours": "4 horas",
    "30 minutes": "30 minutos", "90 minutes": "90 minutos",
    "1 week": "1 semana", "Half day": "Medio día", "Full day": "Día completo",
    "All day 9am–8pm": "Todo el día 9:00–20:00",
    "30 min": "30 min", "1 h": "1 hora", "2 h": "2 horas",
    "2.5 hours": "2,5 horas", "4.5 hours": "4,5 horas", "~4 hours": "~4 horas",
    "~2 hours": "~2 horas", "~90 min": "~90 min", "~1 hour": "~1 hora",
    "1–2 hours": "1–2 horas", "15–30 min": "15–30 min", "30–60 min": "30–60 min",
    "Day pass": "Pase de día", "Custom": "A medida", "Custom length": "Duración a medida",
    "Half a day": "Medio día", "30 minutes": "30 minutos",
    "Per person": "Por persona", "Per group": "Por grupo",
    "Per person · from": "Por persona · desde", "Private group": "Grupo privado",
    "Private group · from": "Grupo privado · desde",
    "Free with any rental": "Gratis con cualquier alquiler",
    "Single flight": "Vuelo individual", "Tandem flight": "Vuelo doble",
    "Triple flight": "Vuelo triple",
    "+1 hour": "+1 hora", "+2 hours": "+2 horas", "+4 hours": "+4 horas",
    "+1 day": "+1 día", "+1 week": "+1 semana",
    "Kids bike · 1 hour": "Bici infantil · 1 hora",
    "Kids bike · all day": "Bici infantil · todo el día",
    "Baby seat": "Silla de bebé", "Trailer · all day": "Remolque · todo el día",
    "Basket add-on": "Cesta adicional",
    "Tandem · 1 hour": "Tándem · 1 hora", "Tandem · all day": "Tándem · todo el día",
    "Side-by-side · 1 hour": "Lado a lado · 1 hora",
    "Side-by-side · all day": "Lado a lado · todo el día",
    "Guided tour · from": "Tour guiado · desde",
    "Sales, parts & service": "Venta, repuestos y taller",
    "Segway i2 SE": "Segway i2 SE", "Segway x2 SE": "Segway x2 SE",
    "Trade-in / used": "Usado / entrega a cuenta",
    "Trikke carving vehicle": "Trikke de carving", "Electric Trikke": "Trikke eléctrico",
    "New electric bike": "Bici eléctrica nueva", "New bicycle": "Bicicleta nueva",
    "Ex-rental cruiser": "Cruiser ex-alquiler",
    "Lower cargo frame": "Bastidor de carga inferior",
    "Reflective shields": "Protectores reflectantes",
    "Integrated lighting system": "Sistema de iluminación integrado",
    "Patroller bag": "Bolsa patrullera", "Front bumper": "Parachoques delantero",
    "Comfort mats": "Alfombrillas de confort", "Accessory bar": "Barra de accesorios",
    "Flat repair": "Reparación de pinchazos",
    "Brake / gear service": "Ajuste de frenos y cambios",
    "Full tune-up": "Puesta a punto completa", "Segway service": "Servicio Segway",
    "Battery diagnostics": "Diagnóstico de batería",

    # units
    "hour": "hora", "unit": "unidad", "bike": "bici", "part": "pieza",
    "job": "trabajo", "guided tour": "tour guiado",

    # meta labels
    "Ages 13+": "Desde 13 años", "Ages 14+": "Desde 14 años",
    "Ages 16+": "Desde 16 años", "Ages 12+": "Desde 12 años",
    "Ages 6+": "Desde 6 años", "All ages": "Todas las edades",
    "Ages 16+ to drive": "Conductor desde 16 años",
    "Helmet + lock": "Casco y candado", "Basket $5": "Cesta $5",
    "Sand-capable": "Apta para arena", "40+ mi range": "Autonomía 40+ millas",
    "Route map": "Mapa de ruta", "2 riders": "2 personas",
    "Priced per group": "Precio por grupo", "Training included": "Entrenamiento incluido",
    "Electric option": "Opción eléctrica", "Guided tours": "Tours guiados",
    "2–4 riders": "2–4 personas", "Canopy": "Toldo", "Basket": "Cesta",
    "Cargo basket": "Cesta de carga", "No balance needed": "Sin equilibrio",
    "Kids + adults": "Niños y adultos", "Pads included": "Protecciones incluidas",
    "All sizes": "Todas las tallas", "Lesson included": "Clase incluida",
    "Baby seats $5": "Sillas de bebé $5", "Trailers": "Remolques",
    "Training wheels": "Ruedines", "Min. 2 riders": "Mínimo 2 personas",
    "Helmet + water": "Casco y agua", "Bike or e-bike": "Bici o e-bike",
    "E-bike included": "E-bike incluida", "Small group": "Grupo reducido",
    "Free with rental": "Gratis con el alquiler", "Evening": "Por la tarde-noche",
    "Any group size": "Cualquier tamaño de grupo",
    "Segway, bike or Trikke": "Segway, bici o Trikke",
    "Hotel pickup": "Recogida en el hotel", "Open top": "Techo abierto",
    "1–2 day pass": "Pase de 1–2 días", "Swim stop": "Parada de baño",
    "Narrated": "Con narración", "No experience": "Sin experiencia",
    "2–3 passengers": "2–3 pasajeros", "New units": "Unidades nuevas",
    "Full warranty": "Garantía completa", "Test ride first": "Prueba antes de comprar",
    "Pedal & electric": "Pedal y eléctrico", "Try before you buy": "Pruébalo antes",
    "New & ex-fleet": "Nuevas y ex-flota", "Serviced": "Revisadas",
    "Warranty": "Con garantía", "Genuine parts": "Repuestos originales",
    "Fitted in store": "Montaje en tienda", "Shipping available": "Con envío",
    "Walk-in": "Sin cita", "Same day": "El mismo día",
    "Bikes, e-bikes, Segways": "Bicis, e-bikes, Segways",

    # tags
    "Most booked": "Lo más reservado", "Rides on sand": "Rueda en la arena",
    "Go further": "Llega más lejos", "Two riders, one battery": "Dos personas, una batería",
    "Our namesake": "El que nos da nombre", "Authorized dealer": "Distribuidor oficial",
    "Ride together": "Rodad juntos", "Extra stable": "Muy estable",
    "Lincoln Rd favorite": "Favorito de Lincoln Rd", "Cruise the strip": "Recorre el paseo",
    "Family ready": "Listo para la familia", "Best first ride": "El mejor primer tour",
    "Celebrity homes": "Casas de famosos", "The full island": "La isla entera",
    "Signature": "El clásico", "Longest ride": "El más largo",
    "After dark": "De noche", "Only here": "Solo aquí",
    "Family favorite": "Favorito en familia", "Street art": "Arte urbano",
    "Golden hour": "Hora dorada", "Your route": "Tu ruta",
    "Free with rental": "Gratis con el alquiler",
    "Most booked day trip": "La excursión más reservada", "Full day": "Día completo",
    "Orientation": "Para ubicarte", "Whole city pass": "Pase de toda la ciudad",
    "Adrenaline": "Adrenalina", "600 feet up": "A 180 metros",
    "From the water": "Desde el agua", "Miami classic": "Clásico de Miami",
    "Bucket list": "De lista de deseos", "Photo run": "Ruta de fotos",
    "Factory authorized dealer": "Distribuidor oficial de fábrica",
    "Our specialty": "Nuestra especialidad", "In stock": "En stock",
    "New & ex-fleet": "Nuevas y ex-flota",

    # route levels and times
    "Easy": "Fácil", "Moderate": "Moderado", "E-bike": "E-bike",
    "45 min": "45 min", "40 min": "40 min", "1 h 15": "1 h 15",
    "1 h": "1 h", "2 h": "2 h", "1 h 30": "1 h 30",

    # mode short labels
    "Walk": "A pie", "Bike": "Bici", "Segway": "Segway",
    "Trikke": "Trikke", "Skates": "Patines",

    # interests
    "Art Deco": "Art Déco", "Beach & ocean": "Playa y mar",
    "Photo spots": "Puntos de foto", "Food & coffee": "Comer y café",
    "Mansions & fame": "Mansiones y fama", "Art & museums": "Arte y museos",
    "Family friendly": "Para familias", "Neon after dark": "Neón de noche",
    "Parks & green": "Parques y verde", "Shopping": "Compras",

    # payment notes
    "One tap on iPhone": "Un toque en iPhone",
    "One tap on Android": "Un toque en Android",
    "Visa, Mastercard, Amex": "Visa, Mastercard, Amex",
    "Pay with your balance": "Paga con tu saldo",
}

TEXTS = {
    # ---------------- fleet ----------------
    "fleet.beach-cruiser.name": "Beach Cruiser",
    "fleet.beach-cruiser.hook": "El clásico de South Beach. Ruedas anchas, sillín cómodo, un solo piñón y cero estrés por el paseo de Ocean Drive.",
    "fleet.fat-tire-bike.name": "Bici Fat Tire de playa",
    "fleet.fat-tire-bike.hook": "Ruedas de diez centímetros pensadas para la arena dura de la orilla. La única bici de aquí con la que puedes rodar por la playa.",
    "fleet.electric-bike.name": "Bicicleta eléctrica",
    "fleet.electric-bike.hook": "Asistencia al pedaleo hasta 32 km/h. Wynwood, Bayside, Downtown y vuelta sin sudar bajo el sol de Miami.",
    "fleet.electric-tandem.name": "Tándem eléctrico",
    "fleet.electric-tandem.hook": "Un tándem con asistencia para dos. El más fuerte marca el ritmo y nadie se queda atrás a mitad del puente.",
    "fleet.trikke.name": "Trikke",
    "fleet.trikke.hook": "El vehículo de tres ruedas que da nombre a esta tienda. Se dirige inclinando el cuerpo, es más fácil que una bici y nada llama más la atención en Ocean Drive.",
    "fleet.segway.name": "Segway",
    "fleet.segway.hook": "Autoequilibrado, divertidísimo y más fácil de lo que parece. Entrenamiento gratis antes de cada salida — y también los vendemos y reparamos.",
    "fleet.side-by-side.name": "Lado a lado y tándem",
    "fleet.side-by-side.hook": "Cuatro ruedas, dos asientos uno al lado del otro — más los tándems clásicos. Hablad todo el camino en vez de gritar por encima del hombro.",
    "fleet.adult-tricycle.name": "Triciclo de adulto",
    "fleet.adult-tricycle.hook": "Tres ruedas, cesta trasera grande y cero equilibrio necesario. La opción para picnics en la playa y pasear tranquilo.",
    "fleet.rollerblades.name": "Patines en línea",
    "fleet.rollerblades.hook": "Patina el Beachwalk como un local. Tallas para toda la familia, protecciones y casco incluidos con cada par.",
    "fleet.longboards.name": "Longboards",
    "fleet.longboards.hook": "Longboards para el Beachwalk y Lincoln Road. Protecciones y casco con cada tabla, y una clase de cinco minutos si es tu primera vez.",
    "fleet.kids-bikes.name": "Bicis infantiles y sillas de bebé",
    "fleet.kids-bikes.hook": "Bicis infantiles de 12 a 24 pulgadas, sillas de bebé, remolques y ruedines. Rueda todo el mundo, nadie se queda en el hotel.",

    # ---------------- tours ----------------
    "tour.ocean-drive-segway-tour.name": "Tour en Segway por Ocean Drive",
    "tour.ocean-drive-segway-tour.hook": "El corto, y por el que casi todos empiezan. Ocean Drive, Lummus Park y el frente de playa en Segway, con entrenamiento incluido.",
    "tour.star-island-segway-tour.name": "Tour en Segway a Star Island",
    "tour.star-island-segway-tour.hook": "Por el MacArthur Causeway y su carril protegido hasta las verjas de Star Island — la terminal de cruceros a un lado, las mansiones al otro.",
    "tour.south-beach-segway-tour.name": "Tour en Segway por South Beach",
    "tour.south-beach-segway-tour.hook": "La versión larga: Ocean Drive, Española Way, Lincoln Road, South Pointe Park y el muelle, con paradas lo bastante largas para hacer fotos de verdad.",
    "tour.art-deco-segway-tour.name": "Tour en Segway por el Art Déco de Miami Beach",
    "tour.art-deco-segway-tour.hook": "Recorre el distrito histórico Art Déco mientras tu guía te explica el Miami Beach de los años 30 — neón, ventanas de ojo de buey, cejas y franjas de velocidad.",
    "tour.millionaires-row-segway-tour.name": "Tour en Segway por Millionaire's Row",
    "tour.millionaires-row-segway-tour.hook": "Hacia el norte por Collins pasando el Faena District, el Fontainebleau y las mansiones frente al mar de Millionaire's Row. Nuestra ruta más larga en Segway.",
    "tour.panoramic-night-chariot-tour.name": "Tour nocturno privado Panoramic Chariot",
    "tour.panoramic-night-chariot-tour.hook": "Privado, de noche y todo iluminado: el neón de Ocean Drive, las luces del puente y el skyline de Downtown reflejado en la bahía de Biscayne.",
    "tour.trikke-tour-south-beach.name": "Tour en Trikke por South Beach",
    "tour.trikke-tour-south-beach.hook": "El tour que no puedes reservar en ningún otro sitio: recorrer South Beach en un Trikke de tres ruedas, dirigiéndolo con el cuerpo. Cinco minutos de práctica y ya estás rodando.",
    "tour.art-deco-bike-tour.name": "Tour en bici por el Art Déco",
    "tour.art-deco-bike-tour.hook": "El distrito Art Déco a ritmo de bicicleta, sin edad mínima y sin necesidad de entrenamiento. La versión familiar de nuestra ruta estrella.",
    "tour.south-beach-coastal-bike-ride.name": "Paseo costero por South Beach",
    "tour.south-beach-coastal-bike-ride.hook": "Un recorrido guiado, llano y sin coches por el Beachwalk hasta South Pointe Park y el muelle, con el Atlántico a tu izquierda todo el camino.",
    "tour.wynwood-downtown-ebike-tour.name": "Tour en e-bike por Wynwood y Downtown",
    "tour.wynwood-downtown-ebike-tour.hook": "Cruza la bahía con motor y recorre los murales de Wynwood, luego el Design District, Bayside y Brickell. Nuestra salida más larga sobre dos ruedas.",
    "tour.sunset-venetian-islands-tour.name": "Paseo al atardecer por las Venetian Islands",
    "tour.sunset-venetian-islands-tour.hook": "Cruza el Venetian Causeway en la hora dorada para ver cómo se encienden las luces del skyline de Downtown al otro lado de la bahía.",
    "tour.private-group-corporate-tour.name": "Tour privado para grupos y empresas",
    "tour.private-group-corporate-tour.hook": "Despedidas de soltera, equipos de empresa, reuniones familiares y rodajes. Eliges los vehículos, la ruta y la hora, y montamos el tour a tu medida.",
    "tour.free-wynwood-bike-tour.name": "Tour gratuito en bici por Wynwood",
    "tour.free-wynwood-bike-tour.hook": "Un recorrido guiado por los murales de Wynwood sin coste cuando alquilas con nosotros. Grupos reducidos, salidas fijas, por orden de llegada.",
    "tour.free-coconut-grove-bike-tour.name": "Tour gratuito en bici por Coconut Grove",
    "tour.free-coconut-grove-bike-tour.hook": "El barrio más antiguo de Miami — banianos, la marina frente a la bahía y Vizcaya — guiado y gratis cuando alquilas con nosotros.",

    # ---------------- adventures ----------------
    "adv.everglades-airboat-adventure.name": "Aventura en hidrodeslizador por los Everglades",
    "adv.everglades-airboat-adventure.hook": "Hasta el Río de Hierba para un recorrido en hidrodeslizador entre los juncos, un espectáculo de fauna y caimanes a corta distancia. Transporte desde South Beach incluido.",
    "adv.key-west-day-trip.name": "Excursión de un día a Key West",
    "adv.key-west-day-trip.hook": "La Overseas Highway entera, con el Seven Mile Bridge incluido, y unas seis horas libres en la isla para Duval Street, Mallory Square y el Southernmost Point.",
    "adv.miami-city-tour.name": "City Tour de Miami",
    "adv.miami-city-tour.hook": "Media jornada por toda la ciudad: Little Havana, Wynwood, el Design District, Brickell, Coconut Grove y vuelta cruzando la bahía.",
    "adv.big-bus-tour-miami.name": "Big Bus turístico con paradas libres",
    "adv.big-bus-tour-miami.hook": "Autobús descapotable de dos pisos con pase de día por Miami y Miami Beach. Bájate en Wynwood, Bayside o Little Havana y coge el siguiente cuando termines.",
    "adv.jet-ski-rental.name": "Alquiler de moto de agua",
    "adv.jet-ski-rental.hook": "A fondo por la bahía de Biscayne con el skyline de Downtown de fondo. Sin licencia y con briefing de seguridad completo antes de salir.",
    "adv.parasailing-south-beach.name": "Parasailing en South Beach",
    "adv.parasailing-south-beach.hook": "A ciento ochenta metros sobre el Atlántico con toda la costa de Miami Beach bajo tus pies. Vuelos individuales, dobles o triples, con remojón opcional.",
    "adv.biscayne-bay-boat-cruise.name": "Crucero por Millionaire's Row en la bahía de Biscayne",
    "adv.biscayne-bay-boat-cruise.hook": "Las mansiones de Star, Palm e Hibiscus Island vistas como deben verse — desde un barco, con el skyline de Downtown detrás.",
    "adv.speedboat-sandbar-tour.name": "Lancha rápida y banco de arena",
    "adv.speedboat-sandbar-tour.hook": "Salida rápida desde la marina y fondeo en el banco de arena donde los locales pasan los domingos, con agua templada hasta la cintura.",
    "adv.helicopter-ride-miami.name": "Vuelo en helicóptero por Miami",
    "adv.helicopter-ride-miami.hook": "Vuelo sobre South Beach, Star Island, el puerto de Miami y el skyline de Downtown. La forma más rápida de entender cómo está trazada esta ciudad.",

    # ---------------- shop ----------------
    "shop.segway-sales.name": "Transportadores personales Segway",
    "shop.segway-sales.hook": "Somos el distribuidor oficial de fábrica de Segway en Miami. Unidades nuevas, garantía completa, entrega por todo el sur de Florida y prueba antes de comprar — en la tienda, sobre Ocean Drive.",
    "shop.trikke-sales.name": "Trikke y Trikke eléctrico",
    "shop.trikke-sales.hook": "El vehículo de carving de tres ruedas que nos da nombre, en versión a pedal y eléctrica. Pruébalo primero en un tour y luego compra el que te gustó.",
    "shop.ebike-sales.name": "Bicicletas eléctricas y bicicletas",
    "shop.ebike-sales.hook": "Bicicletas eléctricas y bicicletas nuevas, más cruisers de ex-alquiler revisados por nuestros propios mecánicos y a una fracción del precio de nuevas.",
    "shop.segway-accessories.name": "Repuestos y accesorios Segway i2",
    "shop.segway-accessories.hook": "La gama completa de repuestos Segway: bastidores de carga inferiores, protectores reflectantes superiores e inferiores, iluminación integrada, bolsa patrullera, parachoques delantero, alfombrillas de confort y la barra de accesorios opcional.",
    "shop.repairs-service.name": "Reparación y taller",
    "shop.repairs-service.hook": "Pinchazos, frenos, cambios, centrado de ruedas, diagnóstico de baterías y puestas a punto completas — para bicis, e-bikes, patinetes y Segways. Los nuestros y los tuyos. La mayoría de las reparaciones sin cita se terminan el mismo día.",

    # ---------------- routes ----------------
    "route.the-beachwalk-classic.name": "El clásico del Beachwalk",
    "route.the-beachwalk-classic.desc": "Todo recto por el Beachwalk asfaltado hasta South Pointe Park y vuelta. Llano, sin coches, con tramos de sombra, y el mejor primer paseo de South Beach.",
    "route.art-deco-neon-loop.name": "Circuito del neón Art Déco",
    "route.art-deco-neon-loop.desc": "Ocean Drive, Collins, Washington y Española Way. Hazlo después de las 19:00, cuando se enciende el neón y todo el distrito se vuelve rosa y turquesa.",
    "route.star-island-&-the-causeway.name": "Star Island y el Causeway",
    "route.star-island-&-the-causeway.desc": "Carril bici protegido por el MacArthur Causeway hasta Palm, Hibiscus y Star Island. Cruceros a un lado, mansiones al otro.",
    "route.venetian-islands-sunset.name": "Atardecer en las Venetian Islands",
    "route.venetian-islands-sunset.desc": "Salto de isla en isla con poco tráfico por el Venetian Causeway. La ruta clásica de la hora dorada, con el skyline de Downtown de frente.",
    "route.wynwood-mural-run.name": "Ruta de murales de Wynwood",
    "route.wynwood-mural-run.desc": "Nuestra ruta en e-bike cruzando la bahía hasta el distrito del arte urbano, con vuelta por el Design District y Bayside. Llévate la batería.",
    "route.north-beach-&-boardwalk.name": "North Beach y el Boardwalk",
    "route.north-beach-&-boardwalk.desc": "Hacia el norte por el paseo, pasando Mid-Beach, el Faena District y el Fontainebleau, hasta el extremo tranquilo de la isla.",
}

TEXTS.update({
    # ---------------- POI: the virtual guide's voice ----------------
    "poi.shop.sub": "Tu punto de partida",
    "poi.shop.story": "Washington con la 14. Casco puesto, agua en la cesta, mapa en el bolsillo. Todo lo que sigue es llano.",
    "poi.espanola.sub": "El pueblo español",
    "poi.espanola.story": "Construida en 1922 como la Spanish Colony de Whitman — un pueblo mediterráneo plantado en Florida. Dos manzanas de estuco rosa, toldos a rayas y mesas en mitad de la calle. Al Capone tuvo un casino en el piso de arriba del número 1421.",
    "poi.lincoln.sub": "El paseo de una milla",
    "poi.lincoln.story": "Morris Lapidus la peatonalizó en 1960 y la llamó una calle para personas, no para coches. Una milla de tiendas, cafés y artistas callejeros. Ata la bici y haz este tramo a pie — no se puede rodar por el paseo.",
    "poi.newworld.sub": "El auditorio de Gehry",
    "poi.newworld.story": "Frank Gehry lo construyó en 2011 con un muro de proyección de 650 metros cuadrados por fuera — en las noches de Wallcast la orquesta toca dentro y el parque la ve en la pared, gratis.",
    "poi.botanical.sub": "Escape verde y gratuito",
    "poi.botanical.story": "Una hectárea de palmeras, orquídeas y un jardín japonés, de entrada libre. El rincón más silencioso a menos de dos kilómetros de Ocean Drive.",
    "poi.bass.sub": "Arte contemporáneo en una caja Art Déco de 1930",
    "poi.bass.story": "Construido en 1930 como biblioteca pública de Miami Beach con piedra keystone — roca de coral de Florida llena de fósiles. Mira las paredes antes de mirar el arte.",
    "poi.boardwalk.sub": "El corredor de uvas de mar",
    "poi.boardwalk.story": "Pasarela elevada entre uvas de mar y palmeras hasta el norte. Las bicis van por el Beachwalk asfaltado de abajo — el tramo de madera es solo para caminar.",
    "poi.beachwalk14.sub": "Sin coches, el mar a tu izquierda",
    "poi.beachwalk14.story": "El camino asfaltado que recorre toda la arena. Sin tráfico, sin semáforos, sin pensar — gira a la derecha para South Pointe o a la izquierda para North Beach.",
    "poi.versace.sub": "Villa Casa Casuarina",
    "poi.versace.story": "Construida en 1930 por Alden Freeman, inspirada en el Alcázar de Colón de Santo Domingo. Gianni Versace la compró en 1992 y fue asesinado en estos escalones en 1997. Hoy es un hotel — y el portal más fotografiado de Florida.",
    "poi.clevelander.sub": "La esquina más ruidosa de Ocean Drive",
    "poi.clevelander.story": "1938, y el bar de piscina que define la banda sonora de Ocean Drive. Pasa de día en bici; vuelve de noche, cuando se enciende el neón.",
    "poi.artdeco.sub": "El inicio del distrito",
    "poi.artdeco.story": "Lo lleva la Miami Design Preservation League, la gente que salvó este distrito de las excavadoras en los años 70. Mapas, exposiciones y la razón por la que estos edificios siguen en pie.",
    "poi.lummus.sub": "Las torres de socorrista de colores",
    "poi.lummus.story": "Diez manzanas de palmeras y arena entre Ocean Drive y el Atlántico. Las torres de socorrista las rediseñó el arquitecto William Lane tras el huracán Andrew, cada una de un color. La de la calle 10 es la de todas las postales.",
    "poi.wolfsonian.sub": "Diseño, propaganda e industria",
    "poi.wolfsonian.story": "Un almacén de 1927 convertido en museo sobre cómo el diseño dio forma al mundo moderno. Solo la fuente del vestíbulo ya justifica la parada.",
    "poi.colony.sub": "El del neón azul",
    "poi.colony.story": "1935, obra de Henry Hohauser. Ese rótulo vertical de neón azul es el objeto más reconocible de Miami Beach — y está mejor al anochecer que a mediodía.",
    "poi.oceandrive5.sub": "Donde empieza el distrito",
    "poi.oceandrive5.story": "La puerta sur del distrito Art Déco. De aquí a la calle 15 está la mayor concentración de arquitectura Art Déco del planeta: unos 800 edificios.",
    "poi.joes.sub": "Abierto desde 1913",
    "poi.joes.story": "Más antiguo que la ciudad que lo rodea. La temporada de cangrejo de piedra va de mediados de octubre a mayo, no aceptan reservas, y la ventanilla de comida para llevar al lado del restaurante es la jugada de los locales.",
    "poi.southpointe.sub": "Donde se acaba la isla",
    "poi.southpointe.story": "Siete hectáreas en el extremo sur, con el faro de 1931 y una explanada hecha para ver los cruceros enfilar Government Cut. La mejor luz del día es aquí, una hora antes del atardecer.",
    "poi.southpointepier.sub": "Cruceros al alcance de la mano",
    "poi.southpointepier.story": "Camina hasta el final del espigón y los barcos pasan tan cerca que se leen los nombres. Los domingos por la tarde el canal entero es barcos.",
    "poi.flamingo.sub": "Donde van los de aquí",
    "poi.flamingo.story": "Tenis, pista de atletismo, piscina y sombra. A cuatro manzanas de Ocean Drive y una ciudad completamente distinta.",
    "poi.sunsetharbour.sub": "La cara de barrio",
    "poi.sunsetharbour.story": "Donde come Miami Beach cuando no está actuando: tostadores de café, una pescadería, nada de neón. Ven aquí a comer, no por las vistas.",
    "poi.belleisle.sub": "La primera de las Venetian Islands",
    "poi.belleisle.story": "Cruza el Venetian Causeway de 1926 y se abre el skyline entero de Downtown al otro lado de la bahía de Biscayne. Poco tráfico, llano, y la mejor hora dorada de la isla.",
    "poi.macarthur.sub": "Star Island y el puerto",
    "poi.macarthur.story": "Carril protegido con la terminal de cruceros a un lado y las verjas de Star, Palm e Hibiscus Island al otro. No se puede entrar en Star Island — es privada — pero la verja es la foto.",
    "poi.faena.sub": "El mamut dorado",
    "poi.faena.story": "Mid-Beach convertido en distrito artístico por Alan Faena. El esqueleto de mamut dorado de Damien Hirst está en una vitrina que se ve desde la calle.",
    "poi.fontainebleau.sub": "1954, y sigue presumiendo",
    "poi.fontainebleau.story": "La obra maestra curva de Morris Lapidus, donde rodó Sinatra y nadó Bond. Entra al vestíbulo — la escalera que no lleva a ninguna parte sigue ahí.",

    # ---------------- reviews ----------------
    "review.0": "El tour en Segway por el Art Déco fue lo mejor del viaje. Veinte minutos de práctica y mi suegra ya bajaba por Ocean Drive como una profesional.",
    "review.1": "Alquilamos cuatro bicis y una silla de bebé para una semana. Nos las llevaron al hotel de la calle 16, nos cambiaron una rueda pinchada esa misma tarde, sin dramas.",
    "review.2": "Nos llevamos las e-bikes a Wynwood y volvimos. Los mejores 89 dólares que gastamos en Miami — vimos más ciudad en un día que en los tres anteriores.",
    "review.3": "Patiné el Beachwalk al atardecer con mis hijos. Protecciones, cascos y buenos consejos sobre dónde ir. Un equipo majísimo.",
    "review.4": "Hacer parasailing sobre South Beach fue irreal. Se reserva en la misma tienda y la tripulación del barco hizo que mi hija de diez años se sintiera totalmente segura.",
    "review.5": "Me arreglaron los frenos de mi propia bici en menos de una hora mientras me tomaba un café. Mecánicos de verdad, precio justo, sitio de locales.",
})

TEXTS.update({
    "faq.0.q": "¿Dónde puedo alquilar una bici en South Beach?",
    "faq.0.a": "En nuestra tienda del 233 de la calle 14, Miami Beach, FL 33139 — a una manzana de Ocean Drive y del Beachwalk. Abrimos todos los días de 9:00 a 20:00. No hace falta reservar y también hacemos entregas por todo South Beach.",
    "faq.1.q": "¿Cuánto cuesta alquilar una bici en Miami Beach?",
    "faq.1.a": "Los beach cruisers empiezan en 12 $ la hora y 28 $ el día completo (de 9:00 a 20:00). Las fat tire desde 18 $/hora, las eléctricas desde 25 $/hora, los triciclos de adulto desde 18 $/hora, los tándems desde 22 $/hora y los patines desde 12 $/hora. Casco, candado y agua incluidos en todos los alquileres.",
    "faq.2.q": "¿En qué consiste la happy hour?",
    "faq.2.a": "Si alquilas entre las 13:00 y las 16:00 te regalamos una hora extra en cualquier bici, triciclo o patines. Vale tanto sin reserva como con reserva, todos los días de la semana.",
    "faq.3.q": "¿Cuánto cuestan los tours en Segway?",
    "faq.3.a": "El tour de Ocean Drive cuesta 49 $ por persona y dura una hora. El de Star Island 69 $, los de South Beach y Art Déco 79 $ cada uno por dos horas, y el de Millionaire's Row 89 $ por 2,5 horas. Todos incluyen entrenamiento y requieren un mínimo de dos personas.",
    "faq.4.q": "¿Qué es un Trikke?",
    "faq.4.a": "Un Trikke es un vehículo de tres ruedas que se dirige inclinando el cuerpo de lado a lado — sin pedales y sin hacer equilibrios. Es la máquina que da nombre a esta tienda, se aprende en unos cinco minutos y lo alquilamos desde 25 $ por 30 minutos.",
    "faq.5.q": "¿Hace falta reservar con antelación?",
    "faq.5.a": "Para los alquileres no: puedes venir directamente cualquier día. Recomendamos reservar en temporada alta (de diciembre a abril) y los fines de semana, y es obligatorio para los tours en Segway, las excursiones de un día, las motos de agua, el parasailing y los vuelos en helicóptero, que tienen horarios fijos.",
    "faq.6.q": "¿Lleváis las bicis a mi hotel?",
    "faq.6.a": "Sí. Entregamos y recogemos en hoteles, Airbnbs y edificios de South Beach y Mid-Beach. La entrega es gratis en alquileres de 24 horas o más dentro de South Beach; los alquileres más cortos y otras zonas tienen una tarifa fija. Las excursiones y aventuras incluyen recogida en el hotel.",
    "faq.7.q": "¿Cuánto tiempo puedo quedarme la bici?",
    "faq.7.a": "Desde una hora hasta 60 días. Las tarifas por día, semana y mes bajan mucho cuanto más tiempo ruedes — una semana cuesta más o menos lo mismo que tres días sueltos.",
    "faq.8.q": "¿Qué incluye el alquiler?",
    "faq.8.a": "Todos los alquileres incluyen casco, candado, una botella de agua, un mapa de rutas de Miami Beach y asistencia telefónica mientras estás fuera. Las cestas y las sillas de bebé cuestan 5 $ cada una.",
    "faq.9.q": "¿Qué edad hay que tener para montar en Segway o en Trikke?",
    "faq.9.a": "Hay que tener al menos 14 años; los menores de 18 deben ir acompañados de un adulto. Cada tour empieza con una sesión de entrenamiento gratuita, así que no hace falta experiencia previa, y los tours en Segway PT no requieren depósito ni al reservar ni en tienda.",
    "faq.10.q": "¿Qué más se puede reservar además de bicis y Segways?",
    "faq.10.a": "Aventuras en hidrodeslizador por los Everglades (4,5 horas, 69 $), excursiones de un día a Key West, city tours de Miami, pases del Big Bus turístico, alquiler de motos de agua, parasailing en South Beach, paseos en barco por la bahía de Biscayne y el banco de arena, y vuelos en helicóptero sobre la ciudad. Todo se puede reservar en tienda, online o por teléfono en el +1-305-830-9440, y la mayoría incluye recogida en el hotel.",
    "faq.11.q": "¿Qué tours guiados hacéis?",
    "faq.11.a": "Doce. Cinco tours en Segway con precio publicado — Ocean Drive 49 $, Star Island 69 $, South Beach 79 $, Art Déco 79 $ y Millionaire's Row 89 $ — más un tour en Trikke por South Beach, un tour en bici por el Art Déco, el paseo costero de South Beach, un tour en e-bike por Wynwood y Downtown, un paseo al atardecer por las Venetian Islands, un tour nocturno privado y tours privados y de empresa totalmente a medida.",
    "faq.12.q": "Algunos tours no muestran precio. ¿Por qué?",
    "faq.12.a": "Esos funcionan con calendarios de temporada o se cobran por grupo, así que la tarifa depende de la fecha, del tamaño del grupo y del operador. Llama al +1-305-830-9440 o reserva online y te damos el precio en el momento — todos son reservables.",
    "faq.13.q": "¿Qué es Ruta Viva?",
    "faq.13.a": "Ruta Viva es nuestro guía turístico virtual gratuito para South Beach. Le dices cómo te mueves — a pie, en cruiser, en bici eléctrica, en Segway, en Trikke o en patines —, cuánto tiempo tienes y qué te interesa, y te monta una ruta desde nuestra puerta del 233 de la calle 14 pasando por los sitios que encajan, y luego te va guiando parada a parada mientras ruedas. Está en la web, así que no hay que instalar ninguna app.",
    "faq.14.q": "¿Necesito una bici para usar Ruta Viva?",
    "faq.14.a": "No. Ir a pie es una de las seis opciones y el distrito Art Déco funciona perfectamente caminando. Para South Pointe, las Venetian Islands o Wynwood sí querrás ruedas — y estamos justo en la línea de salida en cualquier caso.",
    "faq.15.q": "¿Ruta Viva tiene algún coste?",
    "faq.15.a": "No. Es gratis, no hay que registrarse y funciona en el navegador de cualquier móvil. El modo en vivo pide tu ubicación para decirte a qué distancia está la siguiente parada; puedes negarla y seguir la ruta escrita igualmente.",
    "faq.16.q": "¿Puedo extender mi alquiler sin volver a la tienda?",
    "faq.16.a": "Sí. Abre el asistente en cualquier página, toca Extender mi alquiler, escribe el número de ticket de tu recibo y elige cuánto tiempo más quieres — una hora, dos, cuatro, un día o una semana. Pagas desde el móvil con Apple Pay, Google Pay, tarjeta o PayPal y tu hora de devolución se actualiza sola. No hace falta volver pedaleando.",
    "faq.17.q": "¿Qué pasa si ya voy tarde para devolverla?",
    "faq.17.a": "Extiéndela igualmente. El asistente marca el alquiler como vencido y la extensión te cubre desde la hora de devolución original, así que no hay recargo por retraso encima. Si prefieres hablar con alguien, llama al +1-305-830-9440 y lo resolvemos en menos de un minuto.",
    "faq.18.q": "¿Dónde encuentro mi número de ticket?",
    "faq.18.a": "Está en el recibo de papel que te damos en el mostrador y en el email de confirmación, con el formato MBB-1234. Si no lo encuentras, llama al +1-305-830-9440 con el nombre de la reserva y lo buscamos nosotros.",
    "faq.19.q": "¿Vendéis Segways y Trikkes?",
    "faq.19.a": "Sí. Somos el distribuidor oficial de fábrica de Segway en Miami, así que vendemos transportadores personales Segway nuevos con garantía completa, además de Trikkes a pedal y eléctricos, bicicletas eléctricas, bicicletas y la gama completa de repuestos Segway i2 — bastidores de carga, protectores reflectantes, iluminación integrada, bolsas patrulleras, parachoques, alfombrillas y la barra de accesorios. Llama al +1-305-830-9440 para modelos y precios actuales.",
    "faq.20.q": "¿Puedo probar un Segway o un Trikke antes de comprarlo?",
    "faq.20.a": "Sí, y lo recomendamos. Alquila el modelo exacto durante una hora, bájalo por Ocean Drive, y si lo compras descontamos el alquiler del precio de compra.",
    "faq.21.q": "¿Los tours de barrio son realmente gratis?",
    "faq.21.a": "Sí. Los tours guiados en bici por Wynwood y Coconut Grove son gratis si alquilas con nosotros. Salen a horas fijas en grupos reducidos y por orden de llegada, así que pregunta en el mostrador o llama antes para reservar plaza.",
    "faq.22.q": "¿Puedo dejar mi equipaje en la tienda?",
    "faq.22.a": "Sí. Guardamos el equipaje en la tienda mientras ruedas — muy útil el día que dejas el hotel o entre un crucero y un vuelo. También hay baño y wifi gratis.",
    "faq.23.q": "¿Es seguro ir en bici por Miami Beach?",
    "faq.23.a": "Sí. South Beach es llano, compacto y está cubierto de carriles bici protegidos, además del Beachwalk sin coches que recorre toda la arena. La ley de Florida exige casco a los menores de 16 años y nosotros lo damos con cada alquiler.",
    "faq.24.q": "¿Reparáis bicis, e-bikes y patinetes?",
    "faq.24.a": "Sí. En nuestro taller hacemos pinchazos, frenos, cambios, baterías y puestas a punto completas de bicis, e-bikes y patinetes, y la mayoría de las reparaciones sin cita se terminan el mismo día. También somos distribuidor oficial de Segway para venta, repuestos y servicio.",
    "faq.25.q": "¿Cuál es la política de cancelación?",
    "faq.25.a": "Las cancelaciones con 30 días o más de antelación se devuelven íntegras; entre 15 y 30 días, el 50 %; entre 8 y 14 días, el 25 %; y dentro de los 7 días previos no son reembolsables. Todas las reservas se pagan por adelantado en dólares estadounidenses.",
})

PHRASES.update({"30 or 60 min": "30 o 60 min", "90 min": "90 min"})
TEXTS.update({
    "mode.walk.name": "A pie",
    "mode.walk.blurb": "Sin alquilar nada. Perfecto para el distrito Art Déco, lento para cualquier cosa al sur de la calle 5.",
    "mode.cruiser.name": "Beach cruiser",
    "mode.cruiser.blurb": "La opción por defecto. Llana, fácil y te cubre la isla entera.",
    "mode.ebike.name": "Bicicleta eléctrica",
    "mode.ebike.blurb": "Te duplica el alcance. Wynwood y Mid-Beach entran en juego.",
    "mode.segway.name": "Segway",
    "mode.segway.blurb": "Solo con guía — nosotros montamos la ruta y un guía la hace contigo.",
    "mode.trikke.name": "Trikke",
    "mode.trikke.blurb": "Se controla inclinándose. Mejor en los caminos anchos y llanos.",
    "mode.skate.name": "Patines o longboard",
    "mode.skate.blurb": "Solo Beachwalk y Lincoln Road. Evita los puentes.",
})
