# -*- coding: utf-8 -*-
"""Italian content. Proper nouns stay in English on purpose."""

PHRASES = {
    "1 hour": "1 ora", "2 hours": "2 ore", "4 hours": "4 ore",
    "30 minutes": "30 minuti", "90 minutes": "90 minuti",
    "1 week": "1 settimana", "Half day": "Mezza giornata", "Full day": "Giornata intera",
    "All day 9am–8pm": "Tutto il giorno 9–20",
    "30 min": "30 min", "1 h": "1 h", "2 h": "2 h",
    "2.5 hours": "2,5 ore", "4.5 hours": "4,5 ore", "~4 hours": "~4 ore",
    "~2 hours": "~2 ore", "~90 min": "~90 min", "~1 hour": "~1 ora",
    "1–2 hours": "1–2 ore", "15–30 min": "15–30 min", "30–60 min": "30–60 min",
    "Day pass": "Pass giornaliero", "Custom": "Su misura", "Custom length": "Durata su misura",
    "Half a day": "Mezza giornata",
    "Per person": "A persona", "Per group": "A gruppo",
    "Per person · from": "A persona · da", "Private group": "Gruppo privato",
    "Private group · from": "Gruppo privato · da",
    "Free with any rental": "Gratis con qualsiasi noleggio",
    "Single flight": "Volo singolo", "Tandem flight": "Volo in due",
    "Triple flight": "Volo in tre",
    "+1 hour": "+1 ora", "+2 hours": "+2 ore", "+4 hours": "+4 ore",
    "+1 day": "+1 giorno", "+1 week": "+1 settimana",
    "Kids bike · 1 hour": "Bici bimbi · 1 ora",
    "Kids bike · all day": "Bici bimbi · tutto il giorno",
    "Baby seat": "Seggiolino", "Trailer · all day": "Rimorchio · tutto il giorno",
    "Basket add-on": "Cestino aggiuntivo",
    "Tandem · 1 hour": "Tandem · 1 ora", "Tandem · all day": "Tandem · tutto il giorno",
    "Side-by-side · 1 hour": "Affiancata · 1 ora",
    "Side-by-side · all day": "Affiancata · tutto il giorno",
    "Guided tour · from": "Tour guidato · da",
    "Sales, parts & service": "Vendita, ricambi e officina",
    "Segway i2 SE": "Segway i2 SE", "Segway x2 SE": "Segway x2 SE",
    "Trade-in / used": "Usato / permuta", "Trikke carving vehicle": "Trikke da carving",
    "Electric Trikke": "Trikke elettrico", "New electric bike": "Bici elettrica nuova",
    "New bicycle": "Bicicletta nuova", "Ex-rental cruiser": "Cruiser ex noleggio",
    "Lower cargo frame": "Telaio da carico inferiore",
    "Reflective shields": "Scudi riflettenti",
    "Integrated lighting system": "Sistema di illuminazione integrato",
    "Patroller bag": "Borsa patroller", "Front bumper": "Paraurti anteriore",
    "Comfort mats": "Tappetini comfort", "Accessory bar": "Barra accessori",
    "Flat repair": "Riparazione forature", "Brake / gear service": "Freni e cambio",
    "Full tune-up": "Tagliando completo", "Segway service": "Assistenza Segway",
    "Battery diagnostics": "Diagnosi batteria",

    "hour": "ora", "unit": "unità", "bike": "bici", "part": "pezzo",
    "job": "intervento", "guided tour": "tour guidato",

    "Ages 13+": "Dai 13 anni", "Ages 14+": "Dai 14 anni",
    "Ages 16+": "Dai 16 anni", "Ages 12+": "Dai 12 anni",
    "Ages 6+": "Dai 6 anni", "All ages": "Tutte le età",
    "Ages 16+ to drive": "Guida dai 16 anni",
    "Helmet + lock": "Casco e lucchetto", "Basket $5": "Cestino $5",
    "Sand-capable": "Adatta alla sabbia", "40+ mi range": "Autonomia 40+ miglia",
    "Route map": "Mappa del percorso", "2 riders": "2 persone",
    "Priced per group": "Prezzo a gruppo", "Training included": "Addestramento incluso",
    "Electric option": "Versione elettrica", "Guided tours": "Tour guidati",
    "2–4 riders": "2–4 persone", "Canopy": "Tettuccio", "Basket": "Cestino",
    "Cargo basket": "Cestino da carico", "No balance needed": "Nessun equilibrio",
    "Kids + adults": "Bambini e adulti", "Pads included": "Protezioni incluse",
    "All sizes": "Tutte le taglie", "Lesson included": "Lezione inclusa",
    "Baby seats $5": "Seggiolini $5", "Trailers": "Rimorchi",
    "Training wheels": "Rotelle", "Min. 2 riders": "Minimo 2 persone",
    "Helmet + water": "Casco e acqua", "Bike or e-bike": "Bici o e-bike",
    "E-bike included": "E-bike inclusa", "Small group": "Gruppo ristretto",
    "Free with rental": "Gratis col noleggio", "Evening": "Di sera",
    "Any group size": "Gruppi di ogni dimensione",
    "Segway, bike or Trikke": "Segway, bici o Trikke",
    "Hotel pickup": "Ritiro in hotel", "Open top": "Tetto aperto",
    "1–2 day pass": "Pass 1–2 giorni", "Swim stop": "Sosta bagno",
    "Narrated": "Con racconto", "No experience": "Nessuna esperienza",
    "2–3 passengers": "2–3 passeggeri", "New units": "Unità nuove",
    "Full warranty": "Garanzia completa", "Test ride first": "Prova prima di comprare",
    "Pedal & electric": "A pedali ed elettrico", "Try before you buy": "Provalo prima",
    "New & ex-fleet": "Nuove ed ex flotta", "Serviced": "Revisionate",
    "Warranty": "Con garanzia", "Genuine parts": "Ricambi originali",
    "Fitted in store": "Montaggio in negozio", "Shipping available": "Spedizione disponibile",
    "Walk-in": "Senza appuntamento", "Same day": "In giornata",
    "Bikes, e-bikes, Segways": "Bici, e-bike, Segway",

    "Most booked": "Il più prenotato", "Rides on sand": "Va sulla sabbia",
    "Go further": "Vai più lontano", "Two riders, one battery": "Due persone, una batteria",
    "Our namesake": "Quello che ci dà il nome", "Authorized dealer": "Rivenditore autorizzato",
    "Ride together": "Pedalate insieme", "Extra stable": "Molto stabile",
    "Lincoln Rd favorite": "Il preferito di Lincoln Rd", "Cruise the strip": "Percorri il lungomare",
    "Family ready": "Pronto per la famiglia", "Best first ride": "Il miglior primo tour",
    "Celebrity homes": "Case di celebrità", "The full island": "Tutta l'isola",
    "Signature": "Il classico", "Longest ride": "Il più lungo",
    "After dark": "Dopo il tramonto", "Only here": "Solo qui",
    "Family favorite": "Il preferito in famiglia", "Street art": "Street art",
    "Golden hour": "Ora dorata", "Your route": "Il tuo percorso",
    "Most booked day trip": "La gita più prenotata", "Full day": "Giornata intera",
    "Orientation": "Per orientarti", "Whole city pass": "Pass per tutta la città",
    "Adrenaline": "Adrenalina", "600 feet up": "A 180 metri",
    "From the water": "Dall'acqua", "Miami classic": "Un classico di Miami",
    "Bucket list": "Da lista dei desideri", "Photo run": "Giro fotografico",
    "Factory authorized dealer": "Rivenditore autorizzato di fabbrica",
    "Our specialty": "La nostra specialità", "In stock": "Disponibile",

    "Easy": "Facile", "Moderate": "Medio", "E-bike": "E-bike",
    "45 min": "45 min", "40 min": "40 min", "1 h 15": "1 h 15", "1 h 30": "1 h 30",

    "Walk": "A piedi", "Bike": "Bici", "Segway": "Segway",
    "Trikke": "Trikke", "Skates": "Pattini",

    "Art Deco": "Art Déco", "Beach & ocean": "Spiaggia e mare",
    "Photo spots": "Punti fotografici", "Food & coffee": "Cibo e caffè",
    "Mansions & fame": "Ville e celebrità", "Art & museums": "Arte e musei",
    "Family friendly": "Per famiglie", "Neon after dark": "Neon di notte",
    "Parks & green": "Parchi e verde", "Shopping": "Shopping",

    "One tap on iPhone": "Un tocco su iPhone",
    "One tap on Android": "Un tocco su Android",
    "Visa, Mastercard, Amex": "Visa, Mastercard, Amex",
    "Pay with your balance": "Paga col tuo saldo",
}

TEXTS = {
    "fleet.beach-cruiser.name": "Beach Cruiser",
    "fleet.beach-cruiser.hook": "Il classico di South Beach. Gomme larghe, sella comoda, un solo rapporto e zero stress lungo la passeggiata di Ocean Drive.",
    "fleet.fat-tire-bike.name": "Bici Fat Tire da spiaggia",
    "fleet.fat-tire-bike.hook": "Gomme da dieci centimetri pensate per la sabbia compatta sul bagnasciuga. L'unica bici qui con cui puoi davvero pedalare in spiaggia.",
    "fleet.electric-bike.name": "Bicicletta elettrica",
    "fleet.electric-bike.hook": "Pedalata assistita fino a 32 km/h. Wynwood, Bayside, Downtown e ritorno senza sudare sotto il sole di Miami.",
    "fleet.electric-tandem.name": "Tandem elettrico",
    "fleet.electric-tandem.hook": "Un tandem assistito per due. Il più forte detta il ritmo e nessuno resta indietro a metà ponte.",
    "fleet.trikke.name": "Trikke",
    "fleet.trikke.hook": "Il veicolo a tre ruote da cui prende il nome questo negozio. Si guida inclinando il corpo, è più facile di una bici e niente attira più sguardi su Ocean Drive.",
    "fleet.segway.name": "Segway",
    "fleet.segway.hook": "Autobilanciato, divertentissimo e più facile di quanto sembri. Addestramento gratuito prima di ogni uscita — e li vendiamo e ripariamo anche.",
    "fleet.side-by-side.name": "Affiancata e tandem",
    "fleet.side-by-side.hook": "Quattro ruote, due sedili affiancati — più i tandem classici. Chiacchierate per tutto il tragitto invece di urlare da sopra la spalla.",
    "fleet.adult-tricycle.name": "Triciclo per adulti",
    "fleet.adult-tricycle.hook": "Tre ruote, cestino posteriore grande e nessun equilibrio richiesto. La scelta per i picnic in spiaggia e le pedalate tranquille.",
    "fleet.rollerblades.name": "Pattini in linea",
    "fleet.rollerblades.hook": "Pattina il Beachwalk come un local. Taglie per tutta la famiglia, protezioni e casco inclusi con ogni paio.",
    "fleet.longboards.name": "Longboard",
    "fleet.longboards.hook": "Longboard per il Beachwalk e Lincoln Road. Protezioni e casco con ogni tavola, e cinque minuti di lezione se è la prima volta.",
    "fleet.kids-bikes.name": "Bici per bambini e seggiolini",
    "fleet.kids-bikes.hook": "Bici per bambini da 12 a 24 pollici, seggiolini, rimorchi e rotelle. Pedalano tutti, nessuno resta in hotel.",

    "tour.ocean-drive-segway-tour.name": "Tour in Segway su Ocean Drive",
    "tour.ocean-drive-segway-tour.hook": "Il più breve, e quello da cui partono quasi tutti. Ocean Drive, Lummus Park e il lungomare in Segway, addestramento incluso.",
    "tour.star-island-segway-tour.name": "Tour in Segway a Star Island",
    "tour.star-island-segway-tour.hook": "Lungo la MacArthur Causeway sulla pista protetta fino ai cancelli di Star Island — il terminal delle crociere da un lato, le ville dall'altro.",
    "tour.south-beach-segway-tour.name": "Tour in Segway di South Beach",
    "tour.south-beach-segway-tour.hook": "La versione lunga: Ocean Drive, Española Way, Lincoln Road, South Pointe Park e il molo, con soste abbastanza lunghe da fare foto vere.",
    "tour.art-deco-segway-tour.name": "Tour in Segway dell'Art Déco di Miami Beach",
    "tour.art-deco-segway-tour.hook": "Scivola per il distretto storico Art Déco mentre la guida racconta la Miami Beach degli anni Trenta — neon, oblò, sopracciglia e linee di velocità.",
    "tour.millionaires-row-segway-tour.name": "Tour in Segway della Millionaire's Row",
    "tour.millionaires-row-segway-tour.hook": "Verso nord lungo Collins passando il Faena District, il Fontainebleau e le ville sull'oceano della Millionaire's Row. Il nostro percorso in Segway più lungo.",
    "tour.panoramic-night-chariot-tour.name": "Tour notturno privato Panoramic Chariot",
    "tour.panoramic-night-chariot-tour.hook": "Privato, dopo il tramonto e tutto illuminato: il neon di Ocean Drive, le luci del ponte e lo skyline di Downtown riflesso sulla baia di Biscayne.",
    "tour.trikke-tour-south-beach.name": "Tour in Trikke di South Beach",
    "tour.trikke-tour-south-beach.hook": "Il tour che non puoi prenotare da nessun'altra parte: attraversare South Beach su un Trikke a tre ruote, guidandolo col corpo. Cinque minuti di pratica e sei via.",
    "tour.art-deco-bike-tour.name": "Tour in bici dell'Art Déco",
    "tour.art-deco-bike-tour.hook": "Il distretto Art Déco al ritmo della bicicletta, senza età minima e senza addestramento. La versione per famiglie del nostro percorso simbolo.",
    "tour.south-beach-coastal-bike-ride.name": "Pedalata costiera di South Beach",
    "tour.south-beach-coastal-bike-ride.hook": "Un percorso guidato, piatto e senza auto lungo il Beachwalk fino a South Pointe Park e al molo, con l'Atlantico alla tua sinistra per tutto il tempo.",
    "tour.wynwood-downtown-ebike-tour.name": "Tour in e-bike di Wynwood e Downtown",
    "tour.wynwood-downtown-ebike-tour.hook": "Attraversa la baia con il motore e percorri i murales di Wynwood, poi il Design District, Bayside e Brickell. La nostra uscita più lunga su due ruote.",
    "tour.sunset-venetian-islands-tour.name": "Pedalata al tramonto sulle Venetian Islands",
    "tour.sunset-venetian-islands-tour.hook": "Attraversa la Venetian Causeway nell'ora dorata per vedere accendersi lo skyline di Downtown dall'altra parte della baia.",
    "tour.private-group-corporate-tour.name": "Tour privato per gruppi e aziende",
    "tour.private-group-corporate-tour.hook": "Addii al nubilato, team aziendali, riunioni di famiglia e troupe. Scegli i mezzi, il percorso e l'orario e costruiamo il tour attorno a te.",
    "tour.free-wynwood-bike-tour.name": "Tour gratuito in bici di Wynwood",
    "tour.free-wynwood-bike-tour.hook": "Un percorso guidato tra i murales di Wynwood senza costi aggiuntivi se noleggi da noi. Gruppi ristretti, partenze fisse, in ordine di arrivo.",
    "tour.free-coconut-grove-bike-tour.name": "Tour gratuito in bici di Coconut Grove",
    "tour.free-coconut-grove-bike-tour.hook": "Il quartiere più antico di Miami — banani, la marina sulla baia e Vizcaya — guidato e gratuito se noleggi da noi.",

    "adv.everglades-airboat-adventure.name": "Avventura in airboat nelle Everglades",
    "adv.everglades-airboat-adventure.hook": "Fino al Fiume d'Erba per una corsa in airboat tra i giunchi, uno spettacolo di fauna e alligatori da vicino. Trasporto da South Beach incluso.",
    "adv.key-west-day-trip.name": "Gita di un giorno a Key West",
    "adv.key-west-day-trip.hook": "Tutta la Overseas Highway, Seven Mile Bridge compreso, con circa sei ore libere sull'isola per Duval Street, Mallory Square e il Southernmost Point.",
    "adv.miami-city-tour.name": "City tour di Miami",
    "adv.miami-city-tour.hook": "Mezza giornata per tutta la città: Little Havana, Wynwood, il Design District, Brickell, Coconut Grove e ritorno attraverso la baia.",
    "adv.big-bus-tour-miami.name": "Big Bus turistico con salite e discese libere",
    "adv.big-bus-tour-miami.hook": "Bus a due piani scoperto con pass giornaliero per Miami e Miami Beach. Scendi a Wynwood, Bayside o Little Havana e prendi il successivo quando hai finito.",
    "adv.jet-ski-rental.name": "Noleggio moto d'acqua",
    "adv.jet-ski-rental.hook": "Manetta aperta sulla baia di Biscayne con lo skyline di Downtown sullo sfondo. Nessuna patente richiesta e briefing di sicurezza completo prima di partire.",
    "adv.parasailing-south-beach.name": "Parasailing a South Beach",
    "adv.parasailing-south-beach.hook": "A centottanta metri sopra l'Atlantico con tutta la costa di Miami Beach sotto i piedi. Voli singoli, in due o in tre, con tuffo finale facoltativo.",
    "adv.biscayne-bay-boat-cruise.name": "Crociera sulla Millionaire's Row nella baia di Biscayne",
    "adv.biscayne-bay-boat-cruise.hook": "Le ville di Star, Palm e Hibiscus Island viste come andrebbero viste — da una barca, con lo skyline di Downtown alle spalle.",
    "adv.speedboat-sandbar-tour.name": "Motoscafo e banco di sabbia",
    "adv.speedboat-sandbar-tour.hook": "Uscita veloce dalla marina e ancoraggio sul banco di sabbia dove i local passano la domenica, con l'acqua tiepida fino alla vita.",
    "adv.helicopter-ride-miami.name": "Volo in elicottero su Miami",
    "adv.helicopter-ride-miami.hook": "Volo sopra South Beach, Star Island, il porto di Miami e lo skyline di Downtown. Il modo più rapido per capire come è disegnata questa città.",

    "shop.segway-sales.name": "Trasportatori personali Segway",
    "shop.segway-sales.hook": "Siamo il rivenditore autorizzato di fabbrica Segway a Miami. Unità nuove, garanzia completa, consegna in tutta la Florida meridionale e prova su strada prima di comprare — in negozio, su Ocean Drive.",
    "shop.trikke-sales.name": "Trikke e Trikke elettrico",
    "shop.trikke-sales.hook": "Il veicolo da carving a tre ruote da cui prendiamo il nome, nelle versioni a pedali ed elettrica. Provane uno in un tour e poi compra quello che ti è piaciuto.",
    "shop.ebike-sales.name": "Bici elettriche e biciclette",
    "shop.ebike-sales.hook": "Bici elettriche e biciclette nuove, più i cruiser ex noleggio revisionati dai nostri meccanici e venduti a una frazione del prezzo del nuovo.",
    "shop.segway-accessories.name": "Ricambi e accessori Segway i2",
    "shop.segway-accessories.hook": "La gamma completa di ricambi Segway: telai da carico inferiori, scudi riflettenti superiori e inferiori, illuminazione integrata, borsa patroller, paraurti anteriore, tappetini comfort e la barra accessori opzionale.",
    "shop.repairs-service.name": "Riparazioni e officina",
    "shop.repairs-service.hook": "Forature, freni, cambi, centratura ruote, diagnosi batterie e tagliandi completi — per bici, e-bike, monopattini e Segway. I nostri e i vostri. La maggior parte delle riparazioni senza appuntamento è pronta in giornata.",

    "route.the-beachwalk-classic.name": "Il classico del Beachwalk",
    "route.the-beachwalk-classic.desc": "Dritto lungo il Beachwalk asfaltato fino a South Pointe Park e ritorno. Piatto, senza auto, con tratti all'ombra, e la migliore prima pedalata di South Beach.",
    "route.art-deco-neon-loop.name": "Anello del neon Art Déco",
    "route.art-deco-neon-loop.desc": "Ocean Drive, Collins, Washington ed Española Way. Fallo dopo le 19, quando si accende il neon e tutto il distretto diventa rosa e turchese.",
    "route.star-island-&-the-causeway.name": "Star Island e la Causeway",
    "route.star-island-&-the-causeway.desc": "Pista ciclabile protetta lungo la MacArthur Causeway fino a Palm, Hibiscus e Star Island. Navi da crociera da un lato, ville dall'altro.",
    "route.venetian-islands-sunset.name": "Tramonto sulle Venetian Islands",
    "route.venetian-islands-sunset.desc": "Di isola in isola con poco traffico lungo la Venetian Causeway. Il percorso classico dell'ora dorata, con lo skyline di Downtown davanti.",
    "route.wynwood-mural-run.name": "Giro dei murales di Wynwood",
    "route.wynwood-mural-run.desc": "Il nostro percorso in e-bike attraverso la baia fino al distretto della street art, con ritorno per il Design District e Bayside. Porta la batteria.",
    "route.north-beach-&-boardwalk.name": "North Beach e il Boardwalk",
    "route.north-beach-&-boardwalk.desc": "Verso nord lungo il lungomare, oltre Mid-Beach, il Faena District e il Fontainebleau, fino all'estremità tranquilla dell'isola.",
}

TEXTS.update({
    "poi.shop.sub": "Il tuo punto di partenza",
    "poi.shop.story": "Washington angolo 14ª. Casco in testa, acqua nel cestino, mappa in tasca. Da qui in poi è tutto piatto.",
    "poi.espanola.sub": "Il villaggio spagnolo",
    "poi.espanola.story": "Costruita nel 1922 come la Spanish Colony di Whitman — un borgo mediterraneo piantato in Florida. Due isolati di stucco rosa, tende a righe e tavoli in mezzo alla strada. Al Capone teneva un casinò al piano di sopra del numero 1421.",
    "poi.lincoln.sub": "La passeggiata di un miglio",
    "poi.lincoln.story": "Morris Lapidus la rese pedonale nel 1960 e la definì una strada per le persone, non per le auto. Un miglio di negozi, caffè e artisti di strada. Lega la bici e fai questo tratto a piedi — sulla passeggiata non si va su ruote.",
    "poi.newworld.sub": "L'auditorium di Gehry",
    "poi.newworld.story": "Frank Gehry lo costruì nel 2011 con una parete di proiezione di 650 metri quadrati all'esterno — nelle serate Wallcast l'orchestra suona dentro e il parco la guarda sul muro, gratis.",
    "poi.botanical.sub": "Rifugio verde e gratuito",
    "poi.botanical.story": "Un ettaro di palme, orchidee e un giardino giapponese, a ingresso libero. L'angolo più silenzioso entro due chilometri da Ocean Drive.",
    "poi.bass.sub": "Arte contemporanea in un guscio Art Déco del 1930",
    "poi.bass.story": "Costruito nel 1930 come biblioteca pubblica di Miami Beach in pietra keystone — roccia corallina della Florida piena di fossili. Guarda i muri prima di guardare l'arte.",
    "poi.boardwalk.sub": "Il corridoio delle uve di mare",
    "poi.boardwalk.story": "Passerella sopraelevata tra uve di mare e palme fino a nord. Le bici restano sul Beachwalk asfaltato sotto — il tratto in legno è solo per i piedi.",
    "poi.beachwalk14.sub": "Senza auto, il mare alla tua sinistra",
    "poi.beachwalk14.story": "Il percorso asfaltato che corre lungo tutta la sabbia. Niente traffico, niente semafori, niente da pensare — a destra per South Pointe, a sinistra per North Beach.",
    "poi.versace.sub": "Villa Casa Casuarina",
    "poi.versace.story": "Costruita nel 1930 da Alden Freeman, ispirata all'Alcázar de Colón di Santo Domingo. Gianni Versace la comprò nel 1992 e fu ucciso su questi gradini nel 1997. Oggi è un hotel — e il portone più fotografato della Florida.",
    "poi.clevelander.sub": "L'angolo più rumoroso di Ocean Drive",
    "poi.clevelander.story": "1938, e il bar a bordo piscina che definisce la colonna sonora di Ocean Drive. Passaci di giorno; torna dopo il tramonto, quando si accende il neon.",
    "poi.artdeco.sub": "L'inizio del distretto",
    "poi.artdeco.story": "Gestito dalla Miami Design Preservation League, quelli che salvarono questo distretto dalle ruspe negli anni Settanta. Mappe, mostre e il motivo per cui questi edifici sono ancora in piedi.",
    "poi.lummus.sub": "Le torrette dei bagnini colorate",
    "poi.lummus.story": "Dieci isolati di palme e sabbia tra Ocean Drive e l'Atlantico. Le torrette dei bagnini furono ridisegnate dall'architetto William Lane dopo l'uragano Andrew, ognuna di un colore. Quella della 10ª è quella di tutte le cartoline.",
    "poi.wolfsonian.sub": "Design, propaganda e industria",
    "poi.wolfsonian.story": "Un magazzino del 1927 diventato museo su come il design ha plasmato il mondo moderno. Vale la sosta già solo per la fontana dell'atrio.",
    "poi.colony.sub": "Quello col neon blu",
    "poi.colony.story": "1935, di Henry Hohauser. Quell'insegna verticale al neon blu è l'oggetto più riconoscibile di Miami Beach — e rende molto meglio all'imbrunire che a mezzogiorno.",
    "poi.oceandrive5.sub": "Dove comincia il distretto",
    "poi.oceandrive5.story": "La porta sud del distretto Art Déco. Da qui alla 15ª c'è la più grande concentrazione di architettura Art Déco del pianeta: circa 800 edifici.",
    "poi.joes.sub": "Aperto dal 1913",
    "poi.joes.story": "Più vecchio della città che lo circonda. La stagione del granchio di pietra va da metà ottobre a maggio, non accettano prenotazioni, e lo sportello da asporto accanto al ristorante è la mossa dei local.",
    "poi.southpointe.sub": "Dove finisce l'isola",
    "poi.southpointe.story": "Sette ettari sulla punta sud, col faro del 1931 e un prato fatto apposta per guardare le navi da crociera infilare il Government Cut. La luce migliore della giornata è qui, un'ora prima del tramonto.",
    "poi.southpointepier.sub": "Navi da crociera a un braccio di distanza",
    "poi.southpointepier.story": "Cammina fino in fondo al molo e le navi passano abbastanza vicine da leggerne i nomi. La domenica pomeriggio il canale è tutto barche.",
    "poi.flamingo.sub": "Dove vanno davvero i local",
    "poi.flamingo.story": "Tennis, pista d'atletica, piscina e ombra. A quattro isolati da Ocean Drive e una città completamente diversa.",
    "poi.sunsetharbour.sub": "Il lato di quartiere",
    "poi.sunsetharbour.story": "Dove mangia Miami Beach quando non sta recitando: torrefazioni, una pescheria, zero neon. Vieni qui per pranzo, non per il panorama.",
    "poi.belleisle.sub": "La prima delle Venetian Islands",
    "poi.belleisle.story": "Attraversa la Venetian Causeway del 1926 e si apre tutto lo skyline di Downtown dall'altra parte della baia di Biscayne. Poco traffico, piatto, e la migliore ora dorata dell'isola.",
    "poi.macarthur.sub": "Star Island e il porto",
    "poi.macarthur.story": "Pista protetta col terminal delle crociere da un lato e i cancelli di Star, Palm e Hibiscus Island dall'altro. A Star Island non si entra — è privata — ma il cancello è la foto.",
    "poi.faena.sub": "Il mammut dorato",
    "poi.faena.story": "Mid-Beach trasformato in distretto artistico da Alan Faena. Lo scheletro di mammut dorato di Damien Hirst è in una teca che si vede dalla strada.",
    "poi.fontainebleau.sub": "1954, e continua a farsi notare",
    "poi.fontainebleau.story": "Il capolavoro curvo di Morris Lapidus, dove girò Sinatra e nuotò Bond. Entra nell'atrio — la scala che non porta da nessuna parte è ancora lì.",

    "review.0": "Il tour in Segway dell'Art Déco è stato il momento migliore del viaggio. Venti minuti di pratica e mia suocera scendeva Ocean Drive come una professionista.",
    "review.1": "Abbiamo noleggiato quattro bici e un seggiolino per una settimana. Ce li hanno portati in hotel sulla 16ª, ci hanno cambiato una gomma bucata lo stesso pomeriggio, nessun problema.",
    "review.2": "Abbiamo preso le e-bike fino a Wynwood e ritorno. I migliori 89 dollari spesi a Miami — abbiamo visto più città in un giorno che nei tre precedenti.",
    "review.3": "Ho pattinato il Beachwalk al tramonto con i miei figli. Protezioni, caschi e buoni consigli su dove andare. Squadra davvero simpatica.",
    "review.4": "Il parasailing sopra South Beach è stato irreale. Prenotazione facile direttamente in negozio e l'equipaggio ha fatto sentire mia figlia di dieci anni completamente al sicuro.",
    "review.5": "Mi hanno sistemato i freni della mia bici in meno di un'ora mentre prendevo un caffè. Meccanici veri, prezzo onesto, posto da local.",

    "faq.0.q": "Dove posso noleggiare una bici a South Beach?",
    "faq.0.a": "Nel nostro negozio al 233 della 14ª strada, Miami Beach, FL 33139 — a un isolato da Ocean Drive e dal Beachwalk. Siamo aperti tutti i giorni dalle 9 alle 20. Non serve prenotare e consegniamo anche in tutta South Beach.",
    "faq.1.q": "Quanto costa noleggiare una bici a Miami Beach?",
    "faq.1.a": "I beach cruiser partono da 12 $ l'ora e 28 $ per la giornata intera (dalle 9 alle 20). Le fat tire da 18 $/ora, le elettriche da 25 $/ora, i tricicli per adulti da 18 $/ora, i tandem da 22 $/ora e i pattini da 12 $/ora. Casco, lucchetto e acqua inclusi in ogni noleggio.",
    "faq.2.q": "In cosa consiste l'happy hour?",
    "faq.2.a": "Se noleggi tra le 13 e le 16 ti regaliamo un'ora extra su qualsiasi bici, triciclo o paio di pattini. Vale sia senza prenotazione sia con prenotazione, tutti i giorni della settimana.",
    "faq.3.q": "Quanto costano i tour in Segway?",
    "faq.3.a": "Il tour di Ocean Drive costa 49 $ a persona e dura un'ora. Quello di Star Island 69 $, quelli di South Beach e Art Déco 79 $ ciascuno per due ore, e quello della Millionaire's Row 89 $ per 2,5 ore. Tutti includono l'addestramento e richiedono un minimo di due persone.",
    "faq.4.q": "Che cos'è un Trikke?",
    "faq.4.a": "Un Trikke è un veicolo a tre ruote che si guida inclinando il corpo da un lato all'altro — senza pedali e senza stare in equilibrio. È la macchina da cui prende il nome questo negozio, si impara in circa cinque minuti e lo noleggiamo da 25 $ per 30 minuti.",
    "faq.5.q": "Devo prenotare in anticipo?",
    "faq.5.a": "Per i noleggi no: puoi passare direttamente qualsiasi giorno. Consigliamo di prenotare in alta stagione (da dicembre ad aprile) e nei fine settimana, ed è obbligatorio per i tour in Segway, le gite giornaliere, le moto d'acqua, il parasailing e i voli in elicottero, che hanno orari fissi.",
    "faq.6.q": "Consegnate le bici in hotel?",
    "faq.6.a": "Sì. Consegniamo e ritiriamo in hotel, Airbnb e condomini di South Beach e Mid-Beach. La consegna è gratuita per noleggi di 24 ore o più dentro South Beach; i noleggi più brevi e le altre zone hanno una tariffa fissa. Gite e avventure includono il ritiro in hotel.",
    "faq.7.q": "Per quanto tempo posso tenere la bici?",
    "faq.7.a": "Da un'ora fino a 60 giorni. Le tariffe giornaliere, settimanali e mensili scendono parecchio più a lungo pedali — una settimana costa più o meno quanto tre giornate singole.",
    "faq.8.q": "Cosa è incluso nel noleggio?",
    "faq.8.a": "Ogni noleggio include casco, lucchetto, una bottiglia d'acqua, una mappa dei percorsi di Miami Beach e assistenza telefonica mentre sei in giro. Cestini e seggiolini costano 5 $ ciascuno.",
    "faq.9.q": "Che età serve per guidare un Segway o un Trikke?",
    "faq.9.a": "Bisogna avere almeno 14 anni; i minori di 18 devono essere accompagnati da un adulto. Ogni tour inizia con una sessione di addestramento gratuita, quindi non serve esperienza, e i tour in Segway PT non richiedono alcun deposito né alla prenotazione né in negozio.",
    "faq.10.q": "Cos'altro si può prenotare oltre a bici e Segway?",
    "faq.10.a": "Avventure in airboat nelle Everglades (4,5 ore, 69 $), gite giornaliere a Key West, city tour di Miami, pass del Big Bus turistico, noleggio moto d'acqua, parasailing a South Beach, gite in barca sulla baia di Biscayne e al banco di sabbia, e voli in elicottero sulla città. Tutto si prenota in negozio, online o al telefono allo +1-305-830-9440, e quasi tutto include il ritiro in hotel.",
    "faq.11.q": "Quali tour guidati organizzate?",
    "faq.11.a": "Dodici. Cinque tour in Segway con prezzo pubblicato — Ocean Drive 49 $, Star Island 69 $, South Beach 79 $, Art Déco 79 $ e Millionaire's Row 89 $ — più un tour in Trikke di South Beach, un tour in bici dell'Art Déco, la pedalata costiera di South Beach, un tour in e-bike di Wynwood e Downtown, una pedalata al tramonto sulle Venetian Islands, un tour notturno privato e tour privati e aziendali completamente su misura.",
    "faq.12.q": "Alcuni tour non mostrano il prezzo. Perché?",
    "faq.12.a": "Quelli seguono calendari stagionali o si pagano a gruppo, quindi la tariffa dipende dalla data, dalla dimensione del gruppo e dall'operatore. Chiama lo +1-305-830-9440 o prenota online e ti diamo il prezzo subito — sono tutti prenotabili.",
    "faq.13.q": "Che cos'è Rotta Live?",
    "faq.13.a": "Rotta Live è la nostra guida turistica virtuale gratuita per South Beach. Le dici come ti stai muovendo — a piedi, in cruiser, in bici elettrica, in Segway, in Trikke o sui pattini —, quanto tempo hai e cosa ti interessa, e costruisce un percorso dalla nostra porta al 233 della 14ª passando per i luoghi che corrispondono, poi ti guida tappa dopo tappa mentre pedali. È sul sito, quindi non c'è nessuna app da installare.",
    "faq.14.q": "Serve una bici per usare Rotta Live?",
    "faq.14.a": "No. A piedi è una delle sei opzioni e il distretto Art Déco funziona benissimo camminando. Per South Pointe, le Venetian Islands o Wynwood vorrai delle ruote — e noi siamo comunque sulla linea di partenza.",
    "faq.15.q": "Rotta Live ha un costo?",
    "faq.15.a": "No. È gratuita, non serve registrarsi e funziona nel browser di qualsiasi telefono. La modalità dal vivo chiede la posizione per dirti quanto dista la tappa successiva; puoi rifiutare e seguire comunque il percorso scritto.",
    "faq.16.q": "Posso estendere il noleggio senza tornare in negozio?",
    "faq.16.a": "Sì. Apri l'assistente da qualsiasi pagina, tocca Estendi il noleggio, inserisci il numero del biglietto che trovi sulla ricevuta e scegli quanto tempo in più vuoi — un'ora, due, quattro, un giorno o una settimana. Paghi dal telefono con Apple Pay, Google Pay, carta o PayPal e l'orario di riconsegna si sposta da solo. Non serve tornare indietro pedalando.",
    "faq.17.q": "E se sono già in ritardo con la riconsegna?",
    "faq.17.a": "Estendilo lo stesso. L'assistente segnala il noleggio come scaduto e l'estensione ti copre dall'orario di riconsegna originale, quindi non c'è nessuna penale per il ritardo in aggiunta. Se preferisci parlare con qualcuno, chiama lo +1-305-830-9440 e sistemiamo tutto in meno di un minuto.",
    "faq.18.q": "Dove trovo il numero del mio biglietto?",
    "faq.18.a": "È sulla ricevuta cartacea che ti diamo al banco e nell'email di conferma, nel formato MBB-1234. Se non lo trovi, chiama lo +1-305-830-9440 con il nome della prenotazione e lo cerchiamo noi.",
    "faq.19.q": "Vendete Segway e Trikke?",
    "faq.19.a": "Sì. Siamo il rivenditore autorizzato di fabbrica Segway a Miami, quindi vendiamo trasportatori personali Segway nuovi con garanzia completa, oltre a Trikke a pedali ed elettrici, bici elettriche, biciclette e la gamma completa di ricambi Segway i2 — telai da carico, scudi riflettenti, illuminazione integrata, borse patroller, paraurti, tappetini e la barra accessori. Chiama lo +1-305-830-9440 per modelli e prezzi aggiornati.",
    "faq.20.q": "Posso provare un Segway o un Trikke prima di comprarlo?",
    "faq.20.a": "Sì, e lo consigliamo. Noleggia il modello esatto per un'ora, portalo giù per Ocean Drive, e se lo compri scaliamo il noleggio dal prezzo d'acquisto.",
    "faq.21.q": "I tour di quartiere sono davvero gratuiti?",
    "faq.21.a": "Sì. I tour guidati in bici di Wynwood e Coconut Grove sono gratuiti se noleggi da noi. Partono a orari fissi in gruppi ristretti e in ordine di arrivo, quindi chiedi al banco o chiama prima per assicurarti il posto.",
    "faq.22.q": "Posso lasciare i bagagli in negozio?",
    "faq.22.a": "Sì. Teniamo i bagagli in negozio mentre sei in giro — comodissimo il giorno del check-out o tra una crociera e un volo. Ci sono anche il bagno e il wi-fi gratuito.",
    "faq.23.q": "Miami Beach è sicura per andare in bici?",
    "faq.23.a": "Sì. South Beach è piatta, compatta e coperta di piste ciclabili protette, più il Beachwalk senza auto che corre lungo tutta la sabbia. La legge della Florida impone il casco ai minori di 16 anni e noi lo forniamo con ogni noleggio.",
    "faq.24.q": "Riparate bici, e-bike e monopattini?",
    "faq.24.a": "Sì. Nella nostra officina facciamo forature, freni, cambi, batterie e tagliandi completi di bici, e-bike e monopattini, e la maggior parte delle riparazioni senza appuntamento è pronta in giornata. Siamo anche rivenditore autorizzato Segway per vendita, ricambi e assistenza.",
    "faq.25.q": "Qual è la politica di cancellazione?",
    "faq.25.a": "Le cancellazioni con 30 giorni o più di anticipo vengono rimborsate per intero; tra 15 e 30 giorni al 50%; tra 8 e 14 giorni al 25%; e nei 7 giorni precedenti non sono rimborsabili. Tutte le prenotazioni si pagano in anticipo in dollari statunitensi.",
})

PHRASES.update({"30 or 60 min": "30 o 60 min", "90 min": "90 min"})
TEXTS.update({
    "mode.walk.name": "A piedi",
    "mode.walk.blurb": "Senza noleggiare nulla. Ottimo per il distretto Art Déco, lento per tutto ciò che sta oltre la 5ª strada.",
    "mode.cruiser.name": "Beach cruiser",
    "mode.cruiser.blurb": "L'opzione predefinita. Piatta, facile, copre tutta l'isola.",
    "mode.ebike.name": "Bicicletta elettrica",
    "mode.ebike.blurb": "Raddoppia la tua autonomia. Wynwood e Mid-Beach entrano in gioco.",
    "mode.segway.name": "Segway",
    "mode.segway.blurb": "Solo con guida — costruiamo noi il percorso e una guida lo fa con te.",
    "mode.trikke.name": "Trikke",
    "mode.trikke.blurb": "Si guida inclinandosi. Meglio sui percorsi larghi e piatti.",
    "mode.skate.name": "Pattini o longboard",
    "mode.skate.blurb": "Solo Beachwalk e Lincoln Road. Evita i ponti.",
})
