# -*- coding: utf-8 -*-
"""Brazilian Portuguese content. Proper nouns stay in English on purpose."""

PHRASES = {
    "1 hour": "1 hora", "2 hours": "2 horas", "4 hours": "4 horas",
    "30 minutes": "30 minutos", "90 minutes": "90 minutos",
    "1 week": "1 semana", "Half day": "Meio dia", "Full day": "Dia inteiro",
    "All day 9am–8pm": "Dia inteiro 9h–20h",
    "30 min": "30 min", "1 h": "1 h", "2 h": "2 h",
    "2.5 hours": "2,5 horas", "4.5 hours": "4,5 horas", "~4 hours": "~4 horas",
    "~2 hours": "~2 horas", "~90 min": "~90 min", "~1 hour": "~1 hora",
    "1–2 hours": "1–2 horas", "15–30 min": "15–30 min", "30–60 min": "30–60 min",
    "Day pass": "Passe de um dia", "Custom": "Sob medida", "Custom length": "Duração sob medida",
    "Half a day": "Meio dia",
    "Per person": "Por pessoa", "Per group": "Por grupo",
    "Per person · from": "Por pessoa · a partir de", "Private group": "Grupo privado",
    "Private group · from": "Grupo privado · a partir de",
    "Free with any rental": "Grátis com qualquer aluguel",
    "Single flight": "Voo individual", "Tandem flight": "Voo duplo",
    "Triple flight": "Voo triplo",
    "+1 hour": "+1 hora", "+2 hours": "+2 horas", "+4 hours": "+4 horas",
    "+1 day": "+1 dia", "+1 week": "+1 semana",
    "Kids bike · 1 hour": "Bike infantil · 1 hora",
    "Kids bike · all day": "Bike infantil · dia inteiro",
    "Baby seat": "Cadeirinha", "Trailer · all day": "Carretinha · dia inteiro",
    "Basket add-on": "Cesta adicional",
    "Tandem · 1 hour": "Tandem · 1 hora", "Tandem · all day": "Tandem · dia inteiro",
    "Side-by-side · 1 hour": "Lado a lado · 1 hora",
    "Side-by-side · all day": "Lado a lado · dia inteiro",
    "Guided tour · from": "Passeio guiado · a partir de",
    "Sales, parts & service": "Vendas, peças e oficina",
    "Segway i2 SE": "Segway i2 SE", "Segway x2 SE": "Segway x2 SE",
    "Trade-in / used": "Usado / troca", "Trikke carving vehicle": "Trikke de carving",
    "Electric Trikke": "Trikke elétrico", "New electric bike": "Bike elétrica nova",
    "New bicycle": "Bicicleta nova", "Ex-rental cruiser": "Cruiser ex-locação",
    "Lower cargo frame": "Suporte de carga inferior",
    "Reflective shields": "Protetores refletivos",
    "Integrated lighting system": "Sistema de iluminação integrado",
    "Patroller bag": "Bolsa patrulha", "Front bumper": "Para-choque dianteiro",
    "Comfort mats": "Tapetes de conforto", "Accessory bar": "Barra de acessórios",
    "Flat repair": "Conserto de furo", "Brake / gear service": "Revisão de freios e marchas",
    "Full tune-up": "Revisão completa", "Segway service": "Serviço Segway",
    "Battery diagnostics": "Diagnóstico de bateria",

    "hour": "hora", "unit": "unidade", "bike": "bike", "part": "peça",
    "job": "serviço", "guided tour": "passeio guiado",

    "Ages 13+": "A partir de 13 anos", "Ages 14+": "A partir de 14 anos",
    "Ages 16+": "A partir de 16 anos", "Ages 12+": "A partir de 12 anos",
    "Ages 6+": "A partir de 6 anos", "All ages": "Todas as idades",
    "Ages 16+ to drive": "Condutor a partir de 16 anos",
    "Helmet + lock": "Capacete e cadeado", "Basket $5": "Cesta $5",
    "Sand-capable": "Anda na areia", "40+ mi range": "Autonomia 40+ milhas",
    "Route map": "Mapa da rota", "2 riders": "2 pessoas",
    "Priced per group": "Preço por grupo", "Training included": "Treinamento incluído",
    "Electric option": "Opção elétrica", "Guided tours": "Passeios guiados",
    "2–4 riders": "2–4 pessoas", "Canopy": "Cobertura", "Basket": "Cesta",
    "Cargo basket": "Cesta de carga", "No balance needed": "Sem equilíbrio",
    "Kids + adults": "Crianças e adultos", "Pads included": "Proteções incluídas",
    "All sizes": "Todos os tamanhos", "Lesson included": "Aula incluída",
    "Baby seats $5": "Cadeirinhas $5", "Trailers": "Carretinhas",
    "Training wheels": "Rodinhas", "Min. 2 riders": "Mínimo 2 pessoas",
    "Helmet + water": "Capacete e água", "Bike or e-bike": "Bike ou e-bike",
    "E-bike included": "E-bike incluída", "Small group": "Grupo pequeno",
    "Free with rental": "Grátis com o aluguel", "Evening": "À noite",
    "Any group size": "Qualquer tamanho de grupo",
    "Segway, bike or Trikke": "Segway, bike ou Trikke",
    "Hotel pickup": "Busca no hotel", "Open top": "Teto aberto",
    "1–2 day pass": "Passe de 1–2 dias", "Swim stop": "Parada para banho",
    "Narrated": "Com narração", "No experience": "Sem experiência",
    "2–3 passengers": "2–3 passageiros", "New units": "Unidades novas",
    "Full warranty": "Garantia completa", "Test ride first": "Teste antes de comprar",
    "Pedal & electric": "Pedal e elétrico", "Try before you buy": "Experimente antes",
    "New & ex-fleet": "Novas e ex-frota", "Serviced": "Revisadas",
    "Warranty": "Com garantia", "Genuine parts": "Peças originais",
    "Fitted in store": "Instalação na loja", "Shipping available": "Com envio",
    "Walk-in": "Sem agendamento", "Same day": "No mesmo dia",
    "Bikes, e-bikes, Segways": "Bikes, e-bikes, Segways",

    "Most booked": "O mais reservado", "Rides on sand": "Anda na areia",
    "Go further": "Vá mais longe", "Two riders, one battery": "Duas pessoas, uma bateria",
    "Our namesake": "O que nos dá o nome", "Authorized dealer": "Revendedor autorizado",
    "Ride together": "Pedalem juntos", "Extra stable": "Muito estável",
    "Lincoln Rd favorite": "Favorito da Lincoln Rd", "Cruise the strip": "Percorra o calçadão",
    "Family ready": "Pronto para a família", "Best first ride": "O melhor primeiro passeio",
    "Celebrity homes": "Casas de celebridades", "The full island": "A ilha inteira",
    "Signature": "O clássico", "Longest ride": "O mais longo",
    "After dark": "À noite", "Only here": "Só aqui",
    "Family favorite": "Favorito em família", "Street art": "Arte de rua",
    "Golden hour": "Hora dourada", "Your route": "Sua rota",
    "Most booked day trip": "O bate-volta mais reservado", "Full day": "Dia inteiro",
    "Orientation": "Para se situar", "Whole city pass": "Passe da cidade inteira",
    "Adrenaline": "Adrenalina", "600 feet up": "A 180 metros",
    "From the water": "Da água", "Miami classic": "Clássico de Miami",
    "Bucket list": "Lista de desejos", "Photo run": "Rota de fotos",
    "Factory authorized dealer": "Revendedor autorizado de fábrica",
    "Our specialty": "Nossa especialidade", "In stock": "Em estoque",

    "Easy": "Fácil", "Moderate": "Moderado", "E-bike": "E-bike",
    "45 min": "45 min", "40 min": "40 min", "1 h 15": "1 h 15", "1 h 30": "1 h 30",

    "Walk": "A pé", "Bike": "Bike", "Segway": "Segway",
    "Trikke": "Trikke", "Skates": "Patins",

    "Art Deco": "Art Déco", "Beach & ocean": "Praia e mar",
    "Photo spots": "Pontos de foto", "Food & coffee": "Comida e café",
    "Mansions & fame": "Mansões e fama", "Art & museums": "Arte e museus",
    "Family friendly": "Para famílias", "Neon after dark": "Neon à noite",
    "Parks & green": "Parques e verde", "Shopping": "Compras",

    "One tap on iPhone": "Um toque no iPhone",
    "One tap on Android": "Um toque no Android",
    "Visa, Mastercard, Amex": "Visa, Mastercard, Amex",
    "Pay with your balance": "Pague com seu saldo",
}

TEXTS = {
    "fleet.beach-cruiser.name": "Beach Cruiser",
    "fleet.beach-cruiser.hook": "O clássico de South Beach. Pneus largos, banco confortável, uma marcha só e zero estresse pelo calçadão da Ocean Drive.",
    "fleet.fat-tire-bike.name": "Bike Fat Tire de praia",
    "fleet.fat-tire-bike.hook": "Pneus de dez centímetros feitos para a areia dura da beira d'água. A única bike daqui com a qual dá para andar na praia.",
    "fleet.electric-bike.name": "Bicicleta elétrica",
    "fleet.electric-bike.hook": "Assistência ao pedal até 32 km/h. Wynwood, Bayside, Downtown e volta sem suar no sol de Miami.",
    "fleet.electric-tandem.name": "Tandem elétrico",
    "fleet.electric-tandem.hook": "Um tandem com assistência para dois. O mais forte dita o ritmo e ninguém fica para trás no meio da ponte.",
    "fleet.trikke.name": "Trikke",
    "fleet.trikke.hook": "O veículo de três rodas que dá nome a esta loja. Você o conduz inclinando o corpo, é mais fácil que uma bike e nada chama mais atenção na Ocean Drive.",
    "fleet.segway.name": "Segway",
    "fleet.segway.hook": "Autoequilibrado, divertidíssimo e mais fácil do que parece. Treinamento grátis antes de cada saída — e também vendemos e consertamos.",
    "fleet.side-by-side.name": "Lado a lado e tandem",
    "fleet.side-by-side.hook": "Quatro rodas, dois bancos lado a lado — mais os tandems clássicos. Conversem o caminho todo em vez de gritar por cima do ombro.",
    "fleet.adult-tricycle.name": "Triciclo adulto",
    "fleet.adult-tricycle.hook": "Três rodas, cesta traseira grande e nenhum equilíbrio necessário. A escolha para piqueniques na praia e passeios tranquilos.",
    "fleet.rollerblades.name": "Patins in-line",
    "fleet.rollerblades.hook": "Patine o Beachwalk como um local. Tamanhos para a família toda, proteções e capacete inclusos em cada par.",
    "fleet.longboards.name": "Longboards",
    "fleet.longboards.hook": "Longboards para o Beachwalk e a Lincoln Road. Proteções e capacete com cada prancha, e uma aula de cinco minutos se for sua primeira vez.",
    "fleet.kids-bikes.name": "Bikes infantis e cadeirinhas",
    "fleet.kids-bikes.hook": "Bikes infantis de 12 a 24 polegadas, cadeirinhas, carretinhas e rodinhas. Todo mundo pedala, ninguém fica no hotel.",

    "tour.ocean-drive-segway-tour.name": "Passeio de Segway pela Ocean Drive",
    "tour.ocean-drive-segway-tour.hook": "O curto, e por onde quase todo mundo começa. Ocean Drive, Lummus Park e a orla de Segway, com treinamento incluído.",
    "tour.star-island-segway-tour.name": "Passeio de Segway até Star Island",
    "tour.star-island-segway-tour.hook": "Pela MacArthur Causeway e sua ciclovia protegida até os portões de Star Island — o terminal de cruzeiros de um lado, as mansões do outro.",
    "tour.south-beach-segway-tour.name": "Passeio de Segway por South Beach",
    "tour.south-beach-segway-tour.hook": "A versão longa: Ocean Drive, Española Way, Lincoln Road, South Pointe Park e o píer, com paradas longas o suficiente para fotos de verdade.",
    "tour.art-deco-segway-tour.name": "Passeio de Segway pelo Art Déco de Miami Beach",
    "tour.art-deco-segway-tour.hook": "Deslize pelo distrito histórico Art Déco enquanto seu guia explica a Miami Beach dos anos 1930 — neon, janelas redondas, sobrancelhas e faixas de velocidade.",
    "tour.millionaires-row-segway-tour.name": "Passeio de Segway pela Millionaire's Row",
    "tour.millionaires-row-segway-tour.hook": "Para o norte pela Collins passando pelo Faena District, o Fontainebleau e as mansões de frente para o mar da Millionaire's Row. Nossa rota de Segway mais longa.",
    "tour.panoramic-night-chariot-tour.name": "Passeio noturno privativo Panoramic Chariot",
    "tour.panoramic-night-chariot-tour.hook": "Privativo, depois do escurecer e todo iluminado: o neon da Ocean Drive, as luzes da ponte e o skyline de Downtown refletido na baía de Biscayne.",
    "tour.trikke-tour-south-beach.name": "Passeio de Trikke por South Beach",
    "tour.trikke-tour-south-beach.hook": "O passeio que você não reserva em nenhum outro lugar: cortar South Beach num Trikke de três rodas, conduzindo com o corpo. Cinco minutos de treino e você já foi.",
    "tour.art-deco-bike-tour.name": "Passeio de bike pelo Art Déco",
    "tour.art-deco-bike-tour.hook": "O distrito Art Déco no ritmo da bicicleta, sem idade mínima e sem treinamento. A versão para a família da nossa rota principal.",
    "tour.south-beach-coastal-bike-ride.name": "Passeio costeiro por South Beach",
    "tour.south-beach-coastal-bike-ride.hook": "Um trajeto guiado, plano e sem carros pelo Beachwalk até o South Pointe Park e o píer, com o Atlântico à sua esquerda o tempo todo.",
    "tour.wynwood-downtown-ebike-tour.name": "Passeio de e-bike por Wynwood e Downtown",
    "tour.wynwood-downtown-ebike-tour.hook": "Cruze a baía com motor e percorra os murais de Wynwood, depois o Design District, Bayside e Brickell. Nossa saída mais longa sobre duas rodas.",
    "tour.sunset-venetian-islands-tour.name": "Passeio ao pôr do sol pelas Venetian Islands",
    "tour.sunset-venetian-islands-tour.hook": "Atravesse a Venetian Causeway na hora dourada para ver o skyline de Downtown se acender do outro lado da baía.",
    "tour.private-group-corporate-tour.name": "Passeio privativo para grupos e empresas",
    "tour.private-group-corporate-tour.hook": "Despedidas de solteira, equipes de empresa, encontros de família e filmagens. Escolha os veículos, a rota e o horário, e montamos o passeio em volta de você.",
    "tour.free-wynwood-bike-tour.name": "Passeio grátis de bike por Wynwood",
    "tour.free-wynwood-bike-tour.hook": "Um trajeto guiado pelos murais de Wynwood sem custo quando você aluga com a gente. Grupos pequenos, saídas fixas, por ordem de chegada.",
    "tour.free-coconut-grove-bike-tour.name": "Passeio grátis de bike por Coconut Grove",
    "tour.free-coconut-grove-bike-tour.hook": "O bairro mais antigo de Miami — figueiras-de-bengala, a marina de frente para a baía e Vizcaya — guiado e grátis quando você aluga com a gente.",

    "adv.everglades-airboat-adventure.name": "Aventura de airboat nos Everglades",
    "adv.everglades-airboat-adventure.hook": "Até o Rio de Capim para um passeio de airboat entre os juncos, um show de fauna e jacarés de pertinho. Transporte de South Beach incluído.",
    "adv.key-west-day-trip.name": "Bate-volta a Key West",
    "adv.key-west-day-trip.hook": "A Overseas Highway inteira, com a Seven Mile Bridge incluída, e cerca de seis horas livres na ilha para a Duval Street, a Mallory Square e o Southernmost Point.",
    "adv.miami-city-tour.name": "City Tour de Miami",
    "adv.miami-city-tour.hook": "Meio dia pela cidade inteira: Little Havana, Wynwood, o Design District, Brickell, Coconut Grove e volta pela baía.",
    "adv.big-bus-tour-miami.name": "Big Bus turístico com paradas livres",
    "adv.big-bus-tour-miami.hook": "Ônibus de dois andares sem teto com passe de um dia por Miami e Miami Beach. Desça em Wynwood, Bayside ou Little Havana e pegue o próximo quando terminar.",
    "adv.jet-ski-rental.name": "Aluguel de jet ski",
    "adv.jet-ski-rental.hook": "Acelerador aberto na baía de Biscayne com o skyline de Downtown ao fundo. Sem necessidade de habilitação e com briefing de segurança completo antes de sair.",
    "adv.parasailing-south-beach.name": "Parasailing em South Beach",
    "adv.parasailing-south-beach.hook": "A cento e oitenta metros sobre o Atlântico com toda a costa de Miami Beach sob seus pés. Voos individuais, duplos ou triplos, com mergulho opcional.",
    "adv.biscayne-bay-boat-cruise.name": "Cruzeiro pela Millionaire's Row na baía de Biscayne",
    "adv.biscayne-bay-boat-cruise.hook": "As mansões de Star, Palm e Hibiscus Island vistas como deveriam ser — de barco, com o skyline de Downtown atrás.",
    "adv.speedboat-sandbar-tour.name": "Lancha e banco de areia",
    "adv.speedboat-sandbar-tour.hook": "Saída rápida da marina e ancoragem no banco de areia onde os locais passam os domingos, com água morna na altura da cintura.",
    "adv.helicopter-ride-miami.name": "Voo de helicóptero por Miami",
    "adv.helicopter-ride-miami.hook": "Voo sobre South Beach, Star Island, o Porto de Miami e o skyline de Downtown. O jeito mais rápido de entender como esta cidade é desenhada.",

    "shop.segway-sales.name": "Transportadores pessoais Segway",
    "shop.segway-sales.hook": "Somos o revendedor autorizado de fábrica da Segway em Miami. Unidades novas, garantia completa, entrega em todo o sul da Flórida e test drive antes de comprar — na loja, na Ocean Drive.",
    "shop.trikke-sales.name": "Trikke e Trikke elétrico",
    "shop.trikke-sales.hook": "O veículo de carving de três rodas que nos dá o nome, nas versões a pedal e elétrica. Experimente primeiro num passeio e depois compre o que você gostou.",
    "shop.ebike-sales.name": "Bicicletas elétricas e bicicletas",
    "shop.ebike-sales.hook": "Bicicletas elétricas e bicicletas novas, mais cruisers ex-locação revisados pelos nossos próprios mecânicos e por uma fração do preço de novas.",
    "shop.segway-accessories.name": "Peças e acessórios Segway i2",
    "shop.segway-accessories.hook": "A linha completa de peças Segway: suportes de carga inferiores, protetores refletivos superiores e inferiores, iluminação integrada, bolsa patrulha, para-choque dianteiro, tapetes de conforto e a barra de acessórios opcional.",
    "shop.repairs-service.name": "Consertos e oficina",
    "shop.repairs-service.hook": "Furos, freios, marchas, centragem de rodas, diagnóstico de bateria e revisões completas — para bikes, e-bikes, patinetes e Segways. Os nossos e os seus. A maioria dos consertos sem agendamento sai no mesmo dia.",

    "route.the-beachwalk-classic.name": "O clássico do Beachwalk",
    "route.the-beachwalk-classic.desc": "Reto pelo Beachwalk asfaltado até o South Pointe Park e volta. Plano, sem carros, com trechos de sombra, e o melhor primeiro passeio de South Beach.",
    "route.art-deco-neon-loop.name": "Circuito do neon Art Déco",
    "route.art-deco-neon-loop.desc": "Ocean Drive, Collins, Washington e Española Way. Faça depois das 19h, quando o neon acende e o distrito inteiro fica rosa e turquesa.",
    "route.star-island-&-the-causeway.name": "Star Island e a Causeway",
    "route.star-island-&-the-causeway.desc": "Ciclovia protegida pela MacArthur Causeway até Palm, Hibiscus e Star Island. Navios de cruzeiro de um lado, mansões do outro.",
    "route.venetian-islands-sunset.name": "Pôr do sol nas Venetian Islands",
    "route.venetian-islands-sunset.desc": "Pulando de ilha em ilha com pouco trânsito pela Venetian Causeway. A rota clássica da hora dourada, com o skyline de Downtown à frente.",
    "route.wynwood-mural-run.name": "Rota dos murais de Wynwood",
    "route.wynwood-mural-run.desc": "Nossa rota de e-bike cruzando a baía até o distrito da arte de rua, com volta pelo Design District e Bayside. Leve a bateria.",
    "route.north-beach-&-boardwalk.name": "North Beach e o Boardwalk",
    "route.north-beach-&-boardwalk.desc": "Para o norte pelo calçadão, passando por Mid-Beach, o Faena District e o Fontainebleau, até a ponta tranquila da ilha.",
}

TEXTS.update({
    "poi.shop.sub": "Seu ponto de partida",
    "poi.shop.story": "Washington com a 14. Capacete na cabeça, água na cesta, mapa no bolso. Tudo daqui em diante é plano.",
    "poi.espanola.sub": "A vila espanhola",
    "poi.espanola.story": "Construída em 1922 como a Spanish Colony de Whitman — uma vila mediterrânea plantada na Flórida. Dois quarteirões de estuque rosa, toldos listrados e mesas no meio da rua. Al Capone teve um cassino no andar de cima do número 1421.",
    "poi.lincoln.sub": "O calçadão de uma milha",
    "poi.lincoln.story": "Morris Lapidus a tornou exclusiva para pedestres em 1960 e a chamou de uma rua para pessoas, não para carros. Uma milha de lojas, cafés e artistas de rua. Prenda a bike e faça este trecho a pé — não se anda de roda no calçadão.",
    "poi.newworld.sub": "A sala de concertos de Gehry",
    "poi.newworld.story": "Frank Gehry a construiu em 2011 com uma parede de projeção de 650 metros quadrados do lado de fora — nas noites de Wallcast a orquestra toca dentro e o parque assiste na parede, de graça.",
    "poi.botanical.sub": "Refúgio verde e gratuito",
    "poi.botanical.story": "Um hectare de palmeiras, orquídeas e um jardim japonês, de entrada livre. O canto mais silencioso a menos de dois quilômetros da Ocean Drive.",
    "poi.bass.sub": "Arte contemporânea numa casca Art Déco de 1930",
    "poi.bass.story": "Construído em 1930 como a biblioteca pública de Miami Beach em pedra keystone — rocha de coral da Flórida cheia de fósseis. Olhe as paredes antes de olhar a arte.",
    "poi.boardwalk.sub": "O corredor das uvas-da-praia",
    "poi.boardwalk.story": "Passarela elevada entre uvas-da-praia e palmeiras até o norte. As bikes ficam no Beachwalk asfaltado de baixo — o trecho de madeira é só para os pés.",
    "poi.beachwalk14.sub": "Sem carros, o mar à sua esquerda",
    "poi.beachwalk14.story": "O caminho asfaltado que percorre toda a areia. Sem trânsito, sem semáforos, sem pensar — vire à direita para South Pointe ou à esquerda para North Beach.",
    "poi.versace.sub": "Villa Casa Casuarina",
    "poi.versace.story": "Construída em 1930 por Alden Freeman, inspirada no Alcázar de Colón em Santo Domingo. Gianni Versace a comprou em 1992 e foi morto nestes degraus em 1997. Hoje é um hotel — e a porta mais fotografada da Flórida.",
    "poi.clevelander.sub": "A esquina mais barulhenta da Ocean Drive",
    "poi.clevelander.story": "1938, e o bar de piscina que define a trilha sonora da Ocean Drive. Passe de dia; volte depois do escurecer, quando o neon acende.",
    "poi.artdeco.sub": "O começo do distrito",
    "poi.artdeco.story": "Administrado pela Miami Design Preservation League, o pessoal que salvou este distrito das escavadeiras nos anos 1970. Mapas, exposições e o motivo pelo qual esses prédios ainda estão de pé.",
    "poi.lummus.sub": "As torres de salva-vidas coloridas",
    "poi.lummus.story": "Dez quarteirões de palmeiras e areia entre a Ocean Drive e o Atlântico. As torres de salva-vidas foram refeitas pelo arquiteto William Lane depois do furacão Andrew, cada uma de uma cor. A da rua 10 é a de todos os cartões-postais.",
    "poi.wolfsonian.sub": "Design, propaganda e indústria",
    "poi.wolfsonian.story": "Um armazém de 1927 virado museu sobre como o design moldou o mundo moderno. Só a fonte do saguão já vale a parada.",
    "poi.colony.sub": "O do neon azul",
    "poi.colony.story": "1935, de Henry Hohauser. Aquele letreiro vertical de neon azul é o objeto mais reconhecível de Miami Beach — e fica melhor no fim da tarde do que ao meio-dia.",
    "poi.oceandrive5.sub": "Onde o distrito começa",
    "poi.oceandrive5.story": "O portão sul do distrito Art Déco. Daqui até a rua 15 está a maior concentração de arquitetura Art Déco do planeta: cerca de 800 prédios.",
    "poi.joes.sub": "Aberto desde 1913",
    "poi.joes.story": "Mais velho que a cidade em volta. A temporada do siri-pedra vai de meados de outubro a maio, não aceitam reserva, e a janela de viagem ao lado do restaurante é a jogada dos locais.",
    "poi.southpointe.sub": "Onde a ilha acaba",
    "poi.southpointe.story": "Sete hectares na ponta sul, com o farol de 1931 e um gramado feito para ver os navios de cruzeiro entrarem no Government Cut. A melhor luz do dia é aqui, uma hora antes do pôr do sol.",
    "poi.southpointepier.sub": "Navios de cruzeiro a um braço de distância",
    "poi.southpointepier.story": "Caminhe até a ponta do píer e os navios passam perto o suficiente para ler os nomes. Nas tardes de domingo o canal inteiro é barco.",
    "poi.flamingo.sub": "Onde os locais realmente vão",
    "poi.flamingo.story": "Tênis, pista de corrida, piscina e sombra. A quatro quarteirões da Ocean Drive e uma cidade completamente diferente.",
    "poi.sunsetharbour.sub": "O lado de bairro",
    "poi.sunsetharbour.story": "Onde Miami Beach come quando não está se exibindo: torrefações de café, uma peixaria, nada de neon. Venha aqui para almoçar, não pela vista.",
    "poi.belleisle.sub": "A primeira das Venetian Islands",
    "poi.belleisle.story": "Atravesse a Venetian Causeway de 1926 e o skyline inteiro de Downtown se abre do outro lado da baía de Biscayne. Pouco trânsito, plano, e a melhor hora dourada da ilha.",
    "poi.macarthur.sub": "Star Island e o porto",
    "poi.macarthur.story": "Ciclovia protegida com o terminal de cruzeiros de um lado e os portões de Star, Palm e Hibiscus Island do outro. Não dá para entrar em Star Island — é privada — mas o portão é a foto.",
    "poi.faena.sub": "O mamute dourado",
    "poi.faena.story": "Mid-Beach transformado em distrito artístico por Alan Faena. O esqueleto de mamute dourado de Damien Hirst fica numa vitrine que se vê da rua.",
    "poi.fontainebleau.sub": "1954, e ainda se exibindo",
    "poi.fontainebleau.story": "A obra-prima curva de Morris Lapidus, onde Sinatra filmou e Bond nadou. Entre no saguão — a escada que não leva a lugar nenhum continua lá.",

    "review.0": "O passeio de Segway pelo Art Déco foi o melhor da viagem. Vinte minutos de treino e minha sogra já descia a Ocean Drive como profissional.",
    "review.1": "Alugamos quatro bikes e uma cadeirinha por uma semana. Entregaram no nosso hotel na rua 16, trocaram um pneu furado na mesma tarde, sem drama nenhum.",
    "review.2": "Levamos as e-bikes até Wynwood e voltamos. Os melhores 89 dólares que gastamos em Miami — vimos mais cidade em um dia do que nos três anteriores.",
    "review.3": "Patinei o Beachwalk no pôr do sol com meus filhos. Proteções, capacetes e boas dicas de para onde ir. Equipe super gente boa.",
    "review.4": "Fazer parasailing sobre South Beach foi irreal. Reserva fácil na própria loja e a tripulação do barco fez minha filha de dez anos se sentir completamente segura.",
    "review.5": "Consertaram os freios da minha própria bike em menos de uma hora enquanto eu tomava um café. Mecânicos de verdade, preço justo, lugar de local.",

    "faq.0.q": "Onde posso alugar uma bike em South Beach?",
    "faq.0.a": "Na nossa loja na 233 da rua 14, Miami Beach, FL 33139 — a um quarteirão da Ocean Drive e do Beachwalk. Abrimos todos os dias das 9h às 20h. Não precisa reservar e também entregamos em todo South Beach.",
    "faq.1.q": "Quanto custa alugar uma bike em Miami Beach?",
    "faq.1.a": "Os beach cruisers começam em US$ 12 por hora e US$ 28 pelo dia inteiro (das 9h às 20h). As fat tire a partir de US$ 18/hora, as elétricas a partir de US$ 25/hora, os triciclos adultos a partir de US$ 18/hora, os tandems a partir de US$ 22/hora e os patins a partir de US$ 12/hora. Capacete, cadeado e água inclusos em todos os aluguéis.",
    "faq.2.q": "O que é o happy hour?",
    "faq.2.a": "Se você alugar entre 13h e 16h, ganha uma hora extra em qualquer bike, triciclo ou patins. Vale tanto sem agendamento quanto com reserva, todos os dias da semana.",
    "faq.3.q": "Quanto custam os passeios de Segway?",
    "faq.3.a": "O passeio da Ocean Drive custa US$ 49 por pessoa e dura uma hora. O de Star Island US$ 69, os de South Beach e Art Déco US$ 79 cada por duas horas, e o da Millionaire's Row US$ 89 por 2,5 horas. Todos incluem treinamento e exigem no mínimo duas pessoas.",
    "faq.4.q": "O que é um Trikke?",
    "faq.4.a": "Um Trikke é um veículo de três rodas que você conduz inclinando o corpo de um lado para o outro — sem pedais e sem fazer equilíbrio. É a máquina que dá nome a esta loja, aprende-se em cerca de cinco minutos e alugamos a partir de US$ 25 por 30 minutos.",
    "faq.5.q": "Preciso reservar com antecedência?",
    "faq.5.a": "Para aluguéis, não: pode chegar direto em qualquer dia. Recomendamos reservar na alta temporada (de dezembro a abril) e nos fins de semana, e é obrigatório para os passeios de Segway, os bate-voltas, os jet skis, o parasailing e os voos de helicóptero, que têm horários fixos.",
    "faq.6.q": "Vocês entregam bikes no meu hotel?",
    "faq.6.a": "Sim. Entregamos e buscamos em hotéis, Airbnbs e prédios de South Beach e Mid-Beach. A entrega é grátis em aluguéis de 24 horas ou mais dentro de South Beach; aluguéis mais curtos e outras regiões têm uma taxa fixa. Bate-voltas e aventuras incluem busca no hotel.",
    "faq.7.q": "Por quanto tempo posso ficar com a bike?",
    "faq.7.a": "De uma hora até 60 dias. As diárias, semanais e mensais caem bastante quanto mais tempo você pedala — uma semana custa mais ou menos o mesmo que três diárias avulsas.",
    "faq.8.q": "O que está incluso no aluguel?",
    "faq.8.a": "Todos os aluguéis incluem capacete, cadeado, uma garrafa de água, um mapa de rotas de Miami Beach e suporte por telefone enquanto você está na rua. Cestas e cadeirinhas custam US$ 5 cada.",
    "faq.9.q": "Qual a idade mínima para andar de Segway ou Trikke?",
    "faq.9.a": "É preciso ter pelo menos 14 anos; menores de 18 devem estar acompanhados de um adulto. Todo passeio começa com uma sessão de treinamento grátis, então não é preciso experiência, e os passeios de Segway PT não exigem depósito nem na reserva nem na loja.",
    "faq.10.q": "O que mais dá para reservar além de bikes e Segways?",
    "faq.10.a": "Aventuras de airboat nos Everglades (4,5 horas, US$ 69), bate-voltas a Key West, city tours de Miami, passes do Big Bus turístico, aluguel de jet ski, parasailing em South Beach, passeios de barco pela baía de Biscayne e pelo banco de areia, e voos de helicóptero sobre a cidade. Tudo pode ser reservado na loja, online ou por telefone no +1-305-830-9440, e a maioria inclui busca no hotel.",
    "faq.11.q": "Quais passeios guiados vocês fazem?",
    "faq.11.a": "Doze. Cinco passeios de Segway com preço publicado — Ocean Drive US$ 49, Star Island US$ 69, South Beach US$ 79, Art Déco US$ 79 e Millionaire's Row US$ 89 — mais um passeio de Trikke por South Beach, um passeio de bike pelo Art Déco, o trajeto costeiro de South Beach, um passeio de e-bike por Wynwood e Downtown, um passeio ao pôr do sol pelas Venetian Islands, um passeio noturno privativo e passeios privativos e corporativos totalmente sob medida.",
    "faq.12.q": "Alguns passeios não mostram preço. Por quê?",
    "faq.12.a": "Esses funcionam com calendários de temporada ou são cobrados por grupo, então a tarifa depende da data, do tamanho do grupo e do operador. Ligue para o +1-305-830-9440 ou reserve online e damos o preço na hora — todos são reserváveis.",
    "faq.13.q": "O que é a Rota Viva?",
    "faq.13.a": "A Rota Viva é nosso guia turístico virtual gratuito para South Beach. Você diz como está se movendo — a pé, de cruiser, de bike elétrica, de Segway, de Trikke ou de patins —, quanto tempo tem e o que te interessa, e ela monta uma rota a partir da nossa porta na 233 da rua 14 passando pelos pontos que se encaixam, e depois te guia parada por parada enquanto você pedala. Fica no site, então não há app para instalar.",
    "faq.14.q": "Preciso de uma bike para usar a Rota Viva?",
    "faq.14.a": "Não. A pé é uma das seis opções e o distrito Art Déco funciona perfeitamente caminhando. Para South Pointe, as Venetian Islands ou Wynwood você vai querer rodas — e estamos na linha de largada de qualquer jeito.",
    "faq.15.q": "A Rota Viva custa alguma coisa?",
    "faq.15.a": "Não. É grátis, não precisa cadastro e funciona no navegador de qualquer celular. O modo ao vivo pede sua localização para dizer a que distância está a próxima parada; você pode recusar e seguir a rota escrita mesmo assim.",
    "faq.16.q": "Posso estender meu aluguel sem voltar à loja?",
    "faq.16.a": "Sim. Abra o assistente em qualquer página, toque em Estender meu aluguel, digite o número do ticket do seu recibo e escolha quanto tempo a mais quer — uma hora, duas, quatro, um dia ou uma semana. Você paga pelo celular com Apple Pay, Google Pay, cartão ou PayPal e seu horário de devolução se ajusta sozinho. Não precisa voltar pedalando.",
    "faq.17.q": "E se eu já estiver atrasado para devolver?",
    "faq.17.a": "Estenda assim mesmo. O assistente marca o aluguel como atrasado e a extensão cobre você desde o horário de devolução original, então não há multa por atraso por cima. Se preferir falar com alguém, ligue para o +1-305-830-9440 e resolvemos em menos de um minuto.",
    "faq.18.q": "Onde encontro o número do meu ticket?",
    "faq.18.a": "Está no recibo de papel que entregamos no balcão e no e-mail de confirmação, no formato MBB-1234. Se não achar, ligue para o +1-305-830-9440 com o nome da reserva e buscamos para você.",
    "faq.19.q": "Vocês vendem Segways e Trikkes?",
    "faq.19.a": "Sim. Somos o revendedor autorizado de fábrica da Segway em Miami, então vendemos transportadores pessoais Segway novos com garantia completa, além de Trikkes a pedal e elétricos, bicicletas elétricas, bicicletas e a linha completa de peças Segway i2 — suportes de carga, protetores refletivos, iluminação integrada, bolsas patrulha, para-choques, tapetes e a barra de acessórios. Ligue para o +1-305-830-9440 para modelos e preços atuais.",
    "faq.20.q": "Posso experimentar um Segway ou Trikke antes de comprar?",
    "faq.20.a": "Sim, e recomendamos. Alugue o modelo exato por uma hora, desça a Ocean Drive com ele, e se comprar descontamos o aluguel do preço de compra.",
    "faq.21.q": "Os passeios de bairro são realmente grátis?",
    "faq.21.a": "Sim. Os passeios guiados de bike por Wynwood e Coconut Grove são grátis quando você aluga com a gente. Saem em horários fixos, em grupos pequenos e por ordem de chegada, então pergunte no balcão ou ligue antes para garantir vaga.",
    "faq.22.q": "Posso deixar minha bagagem na loja?",
    "faq.22.a": "Sim. Guardamos a bagagem na loja enquanto você pedala — muito útil no dia do check-out ou entre um cruzeiro e um voo. Também tem banheiro e wi-fi grátis.",
    "faq.23.q": "Miami Beach é segura para andar de bike?",
    "faq.23.a": "Sim. South Beach é plana, compacta e coberta de ciclovias protegidas, além do Beachwalk sem carros que percorre toda a areia. A lei da Flórida exige capacete para menores de 16 anos e nós fornecemos em cada aluguel.",
    "faq.24.q": "Vocês consertam bikes, e-bikes e patinetes?",
    "faq.24.a": "Sim. Na nossa oficina fazemos furos, freios, marchas, baterias e revisões completas de bikes, e-bikes e patinetes, e a maioria dos consertos sem agendamento sai no mesmo dia. Também somos revendedor autorizado Segway para vendas, peças e serviço.",
    "faq.25.q": "Qual é a política de cancelamento?",
    "faq.25.a": "Cancelamentos com 30 dias ou mais de antecedência recebem reembolso integral; entre 15 e 30 dias, 50%; entre 8 e 14 dias, 25%; e dentro dos 7 dias anteriores não são reembolsáveis. Todas as reservas são pagas antecipadamente em dólares americanos.",
})

PHRASES.update({"30 or 60 min": "30 ou 60 min", "90 min": "90 min"})
TEXTS.update({
    "mode.walk.name": "A pé",
    "mode.walk.blurb": "Sem alugar nada. Ótimo para o distrito Art Déco, lento para qualquer coisa ao sul da rua 5.",
    "mode.cruiser.name": "Beach cruiser",
    "mode.cruiser.blurb": "A opção padrão. Plana, fácil e cobre a ilha inteira.",
    "mode.ebike.name": "Bicicleta elétrica",
    "mode.ebike.blurb": "Dobra seu alcance. Wynwood e Mid-Beach entram no jogo.",
    "mode.segway.name": "Segway",
    "mode.segway.blurb": "Só com guia — nós montamos a rota e um guia faz ela com você.",
    "mode.trikke.name": "Trikke",
    "mode.trikke.blurb": "Você controla inclinando o corpo. Melhor nos caminhos largos e planos.",
    "mode.skate.name": "Patins ou longboard",
    "mode.skate.blurb": "Só Beachwalk e Lincoln Road. Evite as pontes.",
})
